- src/components/contributors/index.tsx
- src/components/contributors/styles.ts
- src/components/markdown-renderer/index.tsx
- src/components/markdown-renderer/styles.module.css
- src/components/sidebar/styles.ts
- src/messages/language.json
- src/pages/docs/api-guides/[slug].tsx
- src/styles/documentation-page.ts
To fix the layout of the API Guides documentation pages and add the Contributors component.
Documented [here](https://www.notion.so/vtexhandbook/Incrementar-estrutura-de-uma-p-gina-de-API-Guide-d7b904a3afd6412abbac2fad5c8c41a4)
The API Guides documentation pages only render markdown files using the MarkdownRenderer component. The pages should also have the sidebar and a component that shows pictures of the contributors of the corresponding article.
Go to [this page](https://deploy-preview-35--elated-hoover-5c29bf.netlify.app/docs/api-guides/billing-options) and [this one](https://deploy-preview-35--elated-hoover-5c29bf.netlify.app/docs/api-guides/clients), try different screen resolutions and check against the designs at [Figma](https://www.figma.com/file/Lx6sXdrw9KEvtSEKWttmv8/Developer-P …
> Feature/API Guides Documentation Page Layout

- .github/workflows/cypress.yml
To replace the npm commands in the cypress tests workflow with equivalent yarn commands.
The use of `yarn` has been stablished as a pattern for the devportal repository, but the cypress workflow is still using `npm` commands, one of which generated an error for another PR evaluation as its commits added a new project dependency via `yarn add`. 
[Further information about this problem can be accessed here.](https://www.notion.so/vtexhandbook/Cria-o-e-configura-o-do-repo-Rapi-Doc-na-nova-organiza-o-vtexdocs-3f507915435e4ed3a4b167af50d86685#a54ee5b48c53465e8720b940a4c7f5f3)
Verify if this PR has passed on the cypress workflow checks, since it already uses the changes introduced by this PR.
> fix(cypress-workflow): replace npm commands with yarn

- package.json
- src/pages/docs/api-reference/[slug].tsx
- src/utils/get-rapidoc.mjs
- yarn.lock
To add a script capable of fetching and writing the RapiDoc build file, from the vtexdocs/RapiDoc repository, into the devportal repo.
Currently the RapiDoc build is being accessed with a CDN. To achieve better styling on OpenAPI rendering, we now have our own [RapiDoc fork](https://github.com/vtexdocs/RapiDoc), from where we should get the file `dist/rapidoc-min.js` to be used at the devportal.
This PR proposes a script that fetches the file according to the rapidoc version manually defined in the `package.json` and saves it in the path` public/rapidoc/rapidoc-min.js` during the pre-build and pre-dev phases of the app. That file is already being properly referenced for OpenAPI rendering, and the initial version (tag 1.0.0) has already been defined both in the vtexdocs/RapiDoc repository …
> build(rapidoc): add script to fetch rapidoc-min.js from vtexdocs/RapiDoc

- package.json
To add the correct styles to RapiDoc's authentication page.
Documented [here](https://www.notion.so/vtexhandbook/Estilizar-Header-Auth-RapiDoc-852b4a0e757d4ab19d56bec8ec818f0d)
The styles of RapiDoc's authentication page don't match the design of the corresponding section (Header Auth) of the new Developer's Portal, which can be found [here](https://www.figma.com/file/Lx6sXdrw9KEvtSEKWttmv8/Developer-Portal?node-id=3696%3A238901).
Go to [this page](https://deploy-preview-45--elated-hoover-5c29bf.netlify.app/docs/api-reference/catalog#auth) and check against the design at [Figma](https://www.figma.com/file/Lx6sXdrw9KEvtSEKWttmv8/Developer-Portal?node-id=3696%3A238901), keeping in mind only the page title and the API key's labels and inputs were edited, since the page can cease to exist and …
> Feature/Header Auth Section

- package.json
To upgrade the RapiDoc version applied in order to update and style the OpenAPI request section.
Inadequate structure and styling to follow [the expected design](https://www.figma.com/file/Lx6sXdrw9KEvtSEKWttmv8/Developer-Portal?node-id=2150%3A138907) for the section showing the request params(with default values).
Check all changes in this [RapiDoc PR](https://github.com/vtexdocs/RapiDoc/pull/2) and compare this [preview](https://deploy-preview-44--elated-hoover-5c29bf.netlify.app/) with the expected design. If you have any change requests, make them at the [request section PR](https://github.com/vtexdocs/RapiDoc/pull/2).
https://user-images.githubusercontent.com/42784961/172213187-defaa7c6-95ee-4510-bd0f-b2882ed51c95.mp4
> build(rapidoc): update rapidoc version

- src/components/header/index.tsx
Use Ref (react hook) instead of manipulating DOM
In React, accessing DOM elements directly isn't a good practice. Here we can easily change to use of the react hook `useRef` to reference the header.
Besides code review, check if the header still works naturally on [this page](https://deploy-preview-50--elated-hoover-5c29bf.netlify.app/).
> refactor(header): use Ref instead of manipulating DOM

- package.json
To update RapiDoc version so that we can use the breadcrumbs in the authentication section of the API Reference pages.
The RapiDoc version is outdated, it doesn't contain the breadcrumbs component used in the authentication section of the API Reference pages of the Developer's Portal.
Described [here](https://github.com/vtexdocs/RapiDoc/pull/5).
> Feature/RapiDoc Breadcrumbs

- src/components/sidebar-section/index.tsx
- src/components/sidebar/functions.ts
- src/components/sidebar/index.tsx
- src/components/sidebar/styles.ts
- src/components/tooltip/index.tsx
- src/components/tooltip/styles.ts
Update the sidebar style with the new sidebar version in Figma.
The sidebar style is outdated. This PR proposes to fix it.
Go to [this page](https://deploy-preview-59--elated-hoover-5c29bf.netlify.app/) and compare it with this [page in Figma](https://www.figma.com/file/Lx6sXdrw9KEvtSEKWttmv8/Developer-Portal?node-id=6005%3A356944). Also, check the correct [prototype flow here](https://www.figma.com/proto/Lx6sXdrw9KEvtSEKWttmv8/Developer-Portal?node-id=6005%3A356944&scaling=min-zoom&page-id=6005%3A350485&starting-point-node-id=6005%3A356944&show-proto-sidebar=1).
- On the sixth breakpoint (1920px), we need to add the section title on the side of the section icon.
- Also, add the hover and active effects in this title.
- Remove the help icon on the title in the sidebar section component. …
> fix(sidebar): update the sidebar style

- package.json
To update rapidoc version to reflect the change introduced in [this PR](https://github.com/vtexdocs/RapiDoc/pull/6)
When trying to use rapidoc-mini in the Developers Portal, the app throws an error, regarding RapiDoc's breadcrumbs.
> Fix/Breadcrumbs on rapidoc-mini

- package.json
To upgrade the RapiDoc version in order to update the API references response section according to the expected design.
The absence of a response section - which displays possible responses to methods and paths with their respective codes and other attributes - that follows the visual design provided for in figma.
_*NOTE: this contribution only included the restructuring of the response section and the adaptation between available information and the available design project. Future tasks will be destined to improve the modal design._
[Further information about this contribution - such as detailed description, related problems and solutions - can be found here.
](https://www.notion.so/vtexhandbook/Estilizar-Response-section-da-API-reference-df7f70dff349461d9926e68590660902)
[Please access …
> build(rapidoc): update version

- src/pages/docs/api-reference/[slug].tsx
- src/tests/cypress/integration/catalog-API-page.spec.js
- src/tests/cypress/support/commands.js
- src/utils/typings/typings.d.ts
To switch from Rapidoc to rapidoc-mini.
more details [here](https://www.notion.so/vtexhandbook/Substituir-o-uso-do-Rapidoc-pelo-Rapidoc-mini-020f110ed8bd41df8b682bee8b3424fd).
We can handle Rapidoc-mini as a simple component on a page, differently from Rapidoc. This change will allow us to have more freedom to stylize the page. 
You can check the api-reference page with Rapidoc-mini [here](https://deploy-preview-61--elated-hoover-5c29bf.netlify.app/docs/api-reference/catalog).
> refactor: switch from Rapidoc to Rapidoc-mini

- package.json
- to upgrade the RapiDoc version in order to update the API references response section modal
- to review the recently merged custom behavior of the devportal header when the response modal becomes active / inactive
The absence of styling properties - similar to the ones established for the rest of the project - in the modal of the responses section at the API references (solved by updating RapiDoc version in this repo). In addition, this contribution also aims to accept reviews about the behavior of the header according to the modal state ([included by this PR](https://github.com/vtexdocs/devportal/pull/69)).
[Further information and detailed description here](https://www.notion.so/vtexhandbook/Estilizar-reponse-modal-da-API-reference-e79400522c674753be6b367113cbeb2f).
Please [access …
> Chore/update rapidoc and review header (consider modal)

- src/components/sidebar-elements/index.tsx
- src/components/sidebar-section/index.tsx
- src/utils/typings/unionTypes.ts
A função `handleClick` foi implementada para atualizar a rota quando um item da sidebar é selecionado.
O arquivo `navigation.json` foi atualizado, incluindo agora o campo `slugPrefix` no mesmo nível de `documentation`. 
```
{
"navbar": [
{
"documentation": "API Guides",
"slugPrefix": "api-guides",
"categories": [
(...)
```
A finalidade deste campo é compor a rota dos itens da sidebar da seguinte forma: `router.push(`/docs/${slugPrefix}/${slug}`)`
> fix: implement handleclick and slugprefix

- src/pages/api/docs.ts
- src/pages/docs/api-guides/[slug].tsx
- src/utils/escapeCurlyBraces.ts
- src/utils/getDocsPaths.ts
- src/utils/replaceHTMLBlocks.ts
- src/utils/replaceMagicBlocks.ts
- src/utils/string-utils.ts
To add support for rendering HTML inside HTML magic blocks inside markdown files.
Documented [here](https://www.notion.so/vtexhandbook/Tratar-block-html-a9ff83362d5d4523ab1882ddb2498f80)
Some of the portal's documentation files contains magic blocks of several types. The HTML magic blocks inside those files are being rendered like text.
Go to [this page](https://deploy-preview-81--elated-hoover-5c29bf.netlify.app/docs/api-guides/dev-portal-test) and verify there is a red text that says "A Custom HTML block". This came from this [magic block](https://github.com/vtexdocs/dev-portal-content/blob/a6693ebf0afcf2689021185c3b7b5769ce17cb40/docs/guides/Test/dev-portal-test.md?plain=1#L75). Additionally, you may search for other documentation inside the [dev-portal-content …
> Feature/HTML Magic Blocks in Markdown

- next.config.js
- package.json
- src/components/markdown-renderer/components.tsx
- src/components/markdown-renderer/styles.module.css
- src/pages/docs/api-guides/[slug].tsx
- src/utils/remark_plugins/plaiceholder.tsx
- yarn.lock
The Image component from nextjs needs size info to prerender. We needed to get this data before rendering. We now get  this data using plaiceholder. Which also brings us the blurred placeholder.
> feat(images): compiler gets image data before compiling and generates blured placeholder

- .github/workflows/docsearch-scraper.yml
- .gitignore
- algolia/scraper_md.json
- algolia/scraper_openapi.json
- algolia/scripts/scraper.sh
- package.json
Add the action to index DevPortal pages on every merged PRs and the possibility to run locally with the shell script.
[:book: Docs (and keys) here](https://www.notion.so/vtexhandbook/Criar-GitHub-action-para-rodar-crawler-6ba5ef9b8ac54798a3f403c2402de7d8)
The absence of CI/CD about the reindexing of the app pages.
Check the code and try to run the index command (if you're a Linux user).
> feat(devportal-scraper): add scraper action and command to run locally

- src/components/overview-card/index.tsx
- src/utils/replaceMagicBlocks.ts
- src/utils/string-utils.ts
To handle parameters magic blocks inside markdown files so that they are rendered as tables.
The parameters magic blocks inside markdown files are currently being ignored by the markdown renderer. They should be rendered as tables.
Go to [this page](https://deploy-preview-93--elated-hoover-5c29bf.netlify.app/docs/api-guides/dev-portal-test) and check if [this magic block](https://github.com/vtexdocs/dev-portal-content/blob/a6693ebf0afcf2689021185c3b7b5769ce17cb40/docs/guides/Test/dev-portal-test.md?plain=1#L57) is correctly rendered as a table. Additionally, you may search for other documentations in the [dev-portal-content repository](https://github.com/vtexdocs/dev-portal-content/tree/first-docs) that contain parameters magic blocks and check if those are correctly rendered as tables in …
> Feature/Parameters Magic Blocks in Markdown

- src/components/search-input/functions.ts
- src/components/search-input/results-box.tsx
[Docs here](https://www.notion.so/vtexhandbook/Alterar-rotas-de-resultados-da-busca-pra-usar-os-links-relativos-b88f4941f9b94f1b8261b5e5658d189d) 📖 
Change absolute url to relative url
Visit [this deployment](https://deploy-preview-102--elated-hoover-5c29bf.netlify.app/) and check if the URL in searches keeps directing to the correct page.
> fix(search-input): change absolute url to relative url

- src/utils/escapeCurlyBraces.ts
Parsear o frontmatter.
O newContent não estava recebendo o frontmatter, e por isso, o título dos guides não estava sendo renderizado.
Acessar qualquer página de guides e verificar se o título é renderizado
|Before|After|
|------|-----|
| ![Screen Shot 2022-12-20 at 10 06 35](https://user-images.githubusercontent.com/60782333/208674358-a3d4893d-58c4-4775-ae62-15e3d94ac76e.png) | ![Screen Shot 2022-12-20 at 10 06 17](https://user-images.githubusercontent.com/60782333/208674303-80c9722f-81bd-4751-b9de-9b84cf97d401.png)
> fix(escapecurlybraces): pass frontmatter to newContent

- src/components/breadcrumb/index.tsx
- src/components/breadcrumb/styles.ts
- src/components/category-layout/index.tsx
- src/components/category-layout/styles.module.css
- src/components/category-layout/styles.ts
- src/components/contributors/styles.ts
- src/components/documentation-card/functions.ts
- src/components/documentation-card/styles.ts
- src/components/feedback-section/index.tsx
- src/components/feedback-section/styles.ts
- src/components/markdown-renderer/index.tsx
- src/components/see-also-section/styles.ts
- src/components/table-of-contents/styles.ts
- src/pages/docs/api-guides/[slug].tsx
- src/styles/documentation-page.ts
To adjust the content dimensions of API guide pages in last breakpoint (2560px).
In the last breakpoint (2560px), the content is rendered too small, whick makes it difficult for users to read.
Go to [this page](https://deploy-preview-123--elated-hoover-5c29bf.netlify.app/docs/api-guides) and try accessing different documentation pages. Try testing different breakpoints and check if the page content is rendered in an adequate size.
> Fix/Last Breakpoint

- src/components/sidebar-elements/index.tsx
Support `link` type from `navigation.json`
Add link to faststore docs
Check the (Beta) FastStore link at `/docs/storefront-development`
> feat(sidebar-elements): support link type

- src/components/markdown-renderer/index.tsx
- src/components/table-of-contents/styles.ts
- src/styles/documentation-page.ts
To fix the font sizes and spacings in the last breakpoint.
Some users reported that the font was too big and lines were overlapping in the last breakpoint. That is due to incorrect values for font size and line height in documentation pages.
Go to [this page](https://deploy-preview-142--elated-hoover-5c29bf.netlify.app/docs/guides) and try accessing some documentations. Try testing different breakpoints, specially the last one (2560px wide).
> Fix/Spacing in Last Breakpoint

- package.json
Upgrade the rapidoc version. 
Add the tooltip component to the breadcrumbs. Further information can be found [here](https://www.notion.so/vtexhandbook/Adicionar-tooltip-em-breadcrumbs-do-RapiDoc-bf9cb79de822451e82c57be5972d845c).
Open the [preview](https://deploy-preview-146--elated-hoover-5c29bf.netlify.app/), open different api reference pages and check if a tooltip appears in the breadcrumbs that contain ellipsis.
Review comments should be added to the corresponding [RapiDoc pull request](https://github.com/vtexdocs/RapiDoc/pull/14).
> build(package): update rapidoc version

- package.json
- src/pages/docs/api-reference/[slug].tsx
To improve usability of API Reference pages by renaming the schema tab (the one that shows the parameters in an API request/response) and making it the default tab instead of the example one.
Users are not being able to find the parameters for an API request/response easily.
Go to [this page](https://deploy-preview-151--elated-hoover-5c29bf.netlify.app/docs/api-reference/antifraud-provider-protocol#post-/transactions) and check that the schema tab (in the Request Body and Response sections) is now named "Parameters" and is active by default when you open the page (and the example tab is not). Try testing other documentations as well.
> Fix/Schema Tabs

- src/components/newsletter-section/index.tsx
Hide the newsletter subscription section while it is not functional.
Users were trying to subscribe and were confused if the newsletter subscription was working.
Open the preview and check if the newsletter subscription section is not visible and the page layout is not broken.
> fix(newsletter): hiding newsletter subscription

- public/navigation.json
- src/components/sidebar-elements/index.tsx
Quando `method` não é especificado para páginas do tipo `openapi`, a sidebar resolve a rota da seguinte forma:
```
const pathSuffix = method ? `#${method.toLowerCase()}-${endpoint}` : ''
```
Isso permite renderizar as páginas de overview de OpenAPI - considerando as devidas atualizações no `navigation.json`
Mostrar página de overview das api references
Acessar as páginas de overview da seção API reference
> fix(sidebar-elements): update the route for openapis without method

- src/components/markdown-renderer/components.tsx
- src/components/markdown-renderer/styles.module.css
To limit table width by creating a div container and showing horizontal scrollbar if the table is too large.
Tables that were too wide were extending beyond the limits of the page's content.
Try accessing, in the [preview](https://deploy-preview-161--elated-hoover-5c29bf.netlify.app/), pages that contain large tables and check if the width is limited as expected.
Try accessing these pages in different resolutions.
Example of pages that should be tested:
- [Add To Cart Button](https://deploy-preview-161--elated-hoover-5c29bf.netlify.app/docs/guides/vtex-add-to-cart-button)
- [Autocomplete](https://deploy-preview-161--elated-hoover-5c29bf.netlify.app/docs/guides/vtex-search-autocomplete)
- [Login SSO](https://deploy-preview-161--elated-hoover-5c29bf.netlify.app/docs/guides/login-integration- …
> Fixing table overflow in API Guide pages

- package.json
Update the RapiDoc version.
Now is possible to send API requests in the API reference pages.
Open the [preview](https://deploy-preview-174--elated-hoover-5c29bf.netlify.app/) and try to do different api requests and check if the answer matches the expected one obtained by executing the curl code.
Review comments should be added to the [corresponding rapidoc PR](https://github.com/vtexdocs/RapiDoc/pull/20).
[Further information can be found here.](https://www.notion.so/vtexhandbook/Executar-request-nas-p-ginas-de-API-Reference-f49c0d1a7d9e401897c18367e2743c53)
> build: update rapidoc version to have working api requests

- src/pages/docs/guides/[slug].tsx
- src/utils/escapeCurlyBraces.ts
To improve the log message when incorrectly formatted code blocks are found inside a markdown file and allow such pages to render despite the error.
It is difficult for the tech writers to fix the incorrectly formatted code blocks inside markdown files with no information about where are the unmatched backticks. Also, a lot of pages are not being rendered because of that error.
Try acessing these pages and make sure they are being rendered (they don't 404):
- [asynchronous-integration](https://deploy-preview-153--elated-hoover-5c29bf.netlify.app/docs/guides/asynchronous-integration)
- [starting-to-work-on-master-data-with-json-schema](https://deploy-preview-153--elated-hoover-5c29bf.netlify.app/docs/guides/starting-to-work-on-master-data-with-json-schema)
- …
> Fix/Missing Backtick

- public/navigation.json
Adding a missing page (gift list migration documentation) to navigation.json. Relates to https://github.com/vtexdocs/dev-portal-content/pull/145.
> fix: add list migration doc to navigation.json

- src/components/breadcrumb/index.tsx
- src/components/breadcrumb/styles.ts
- src/components/contributors/styles.ts
- src/components/documentation-card/functions.ts
- src/components/documentation-card/index.tsx
- src/components/documentation-card/styles.ts
- src/components/feedback-section/index.tsx
- src/components/feedback-section/styles.ts
- src/components/header/styles.ts
- src/components/page-header/styles.ts
- src/components/release-note/styles.ts
- src/components/release-section/index.tsx
- src/components/release-section/styles.tsx
- src/components/search-results/styles.ts
- src/components/search-sections/styles.ts
- src/components/see-also-section/styles.ts
- src/components/table-of-contents/index.tsx
- src/components/table-of-contents/styles.ts
- src/components/whats-next-card/styles.ts
- src/pages/updates/release-notes/index.tsx
- src/styles/documentation-landing-page.ts
- src/styles/documentation-page.ts
- src/styles/release-notes.ts
- src/styles/search-page.ts
To fix the layout of some of the portal's pages in some breakpoints.
Some of the portal's pages don't have the correct layout and sizes for some breakpoints (specially the 2560px wide one), according to the designs at https://www.figma.com/file/Lx6sXdrw9KEvtSEKWttmv8/Developer-Portal?node-id=6005%3A350485&t=D9AYHlD9w90KluBr-0 and https://www.figma.com/file/QeNbcHLkqTAury0bNhkpzS/Developers-portal---Screens-2560px?node-id=0%3A1&t=3L9Ph99lex92pj7C-0.
Go to [this website](https://deploy-preview-180--elated-hoover-5c29bf.netlify.app/) and try accessing different pages with different window sizes. Look for differences between the expected layout and the actual one. Keep in mind some pages are not 100% responsive yet. The following fixes are yet to be implemented:
- Add pagination to the first …
> Fix/Responsive Design

- src/components/search-input/customHighlight.tsx
- src/components/search-input/results-box.tsx
- src/components/search-input/styles.ts
Add highlights to search results
Improve the user experience by highlighting the results and showing relevant words.
Go to [this page](https://deploy-preview-183--elated-hoover-5c29bf.netlify.app/) and try to search for something.
|before|after|
|------|------|
|![image](https://user-images.githubusercontent.com/42784961/212772372-f1174326-1e75-43df-8c11-2a735f8ac3c4.png)|![image](https://user-images.githubusercontent.com/42784961/212772322-8558b81f-4423-4fbf-a550-ae682aa42730.png)|
> feat(search-input): custom highlighting to search results

- src/pages/docs/guides/rehypeBlockquote.js
Show whitespace between text and link inside a callout.
Fixing problem reported in user feedback.
Open the [preview](https://deploy-preview-181--elated-hoover-5c29bf.netlify.app/docs/guides/profile-system) and check if in the callouts the links are rendered with a space separating them from the rest of the text.
_Other problems can be noted in some callouts: a leading character that does not render correctly and looks like the text has a extra whitespace, the string contains \n instead of breaking a new line. These problems will be fixed in other tasks._
Before:
After:
> fix(blockquote): use trimStart instead of trim

- public/navigation.json
Adding the following Catalog API endpoints to navigation.json:
- [Get SKU Service](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/skuservice/-skuServiceId-)
- [Get SKU Service Value](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/skuservicevalue/-skuServiceValueId-)
- [Get SKU Service Type](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/skuservicetype/-skuServiceTypeId-)
> fix(navigation): add SKU Service endpoints to navigation.json

- public/navigation.json
Adding the Catalog API - [Get Gift List](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/addon/pvt/giftlist/get/-listId-) endpoint documentation to navigation.json.
> docs(navigation): add get gift list endpoint

- src/styles/global.css
To fix rendering of the http methods in the api guides.
Missing css classes.
Open any API Guide page, such as External seller connector, that contains the keywords (post, get, put, delete, patch) and check if it is highlighted as expected.
> fix(global.css): create css classes for http methods

- src/components/search-input/index.tsx
- src/components/search-input/results-box.tsx
Stop the search with an empty query
On the first page load, the search component creates an empty query to Algolia. This PR aims to reduce the number of unnecessary requests.
> perf(search-input): stop search with an empty query

- package.json
:warning: Review comments should be added to the [corresponding rapidoc PR](https://github.com/vtexdocs/RapiDoc/pull/24).
:warning: This PR should be merged after merging the Rapidoc branch and updating the version tag.
Upgrade rapidoc version to add the option to choose the code example language (between python, node and shell).
The only language available was shell.
Open the [preview](https://deploy-preview-225--elated-hoover-5c29bf.netlify.app/) and check the code in different api reference pages.
> build: update rapidoc version to add language selection

- public/navigation.json
remove Add log in orders from navigation
This endpoint used to be hidden from navigation in the old Developer Portal, now it is necessary to remove it, since the team doesn't want to give visibility to this endpoint.
> remove Add log in orders from navigation

- public/navigation.json
Fixing navigation links for Sessions API endpoints.
Due to openapi path fixes in the sessions API the navigation had wrong links.
> docs(navigation): fix sessions endpoints that have had the paths fixed

- src/components/markdown-renderer/components.tsx
- src/messages/language.json
To handle errors when an image is not loaded correctly. If the NextJs image component is not loaded correctly, a regular img element will be used, if the error persists, an error message will appear.
The alternative text shown when the image was not loaded was not helpful.
Open the [preview](https://deploy-preview-283--elated-hoover-5c29bf.netlify.app/) and check if the images are rendered correctly or are replaced by the error message.
> fix: handle image loading errors

- src/components/sidebar/index.tsx
- src/utils/navigation-utils.ts
To fix problem in which the wrong sidebar endpoint was expanded because the endpoint was the same to the one selected.
The sidebar did show the open documentation correctly.
Open a endpoint that is not unique and check if the sidebar is correct. Example:
Payment Provider Protocol > Configuration Flow > Create Authorization Token (Post) (endpoint is /authorization/token)
Antifraud Provider > OAuth Flow -> 1. Retrieve Token (endpoint also is /authorization/token)
> fix(sidebar): check the parent to expand the correct endpoint

- public/navigation.json
- src/pages/api/openapi/[slug].tsx
- src/utils/getReferencePaths.ts
Adding shipping network endpoints to navigation.
Using our preview.
> Shipping network api

- public/navigation.json
There was a missing `-` in the URL listed for the Notify Carrier with App endpoint that caused a 404.
> docs: changed url in navigation.json

- public/navigation.json
Adding the Master Data v2 orders entity breaking change release note to navigation.
> Orders mdv2 entity breaking change - Release note - Navigation

- package-lock.json
- src/components/JsonEditorIndex/index.tsx
- src/components/JsonEditorIndex/styles.ts
- src/pages/editor/api-index.tsx
- yarn.lock
Creating a tool to automatically generate an API reference index when given a navigation.json API reference object or the content of that object's children array. The goal is to be able to quickly create an index that can be added to the API's [overview](https://github.com/vtex/openapi-schemas/blob/master/Template%20-%20API%20Reference%20Overview.md).
1. Go to `/editor/api-index`.
2. Use the example object (Catalog API from navigation.json) or insert your own.
3. Click `Submit`.
The result will be markdown code for an index of all that API's endpoints, to be used in the API's [overview](https://github.com/vtex/openapi-schemas/blob/master/Template%20-%20API%20Reference%20Overview.md).
**Input**
**Result**
> feat: create api ref index generator tool

- src/pages/docs/api-reference/[slug].tsx
Retrieve the title and description of patch-type endpoints and OpenAPI overviews
code refactoring
Before, we only matched if an endpoint have type: 'get', 'post', 'delete', or 'put' but not 'patch'. I will refactor the code to get the type from constants to be easier to update after.
Check different endpoint types in the preview if the meta "doctitle:" has content.
> fix(api-reference): retrieve missing title and description from reference pages

- src/components/markdown-renderer/components.tsx
To show gifs correctly.
NextJs image optimization doesn't work with gifs, causing gifs to appear as static images.
Open the [preview](https://deploy-preview-355--elated-hoover-5c29bf.netlify.app/) and check if gifs are working as expected. [Example](https://deploy-preview-355--elated-hoover-5c29bf.netlify.app/docs/guides/checkout-overview).
Mostrando como gif está aparecendo atualmente no portal e como deveria estar:
https://user-images.githubusercontent.com/62757720/235165991-f4934bde-6ae8-45f8-9b9c-5e013e59ab57.mp4
> fix: nextjs shouldn't optimize image if it is a gif

- netlify.toml
The goal is to redirect [this doc](https://vtex.io/docs/recipes/store-management/enabling-order-form-optimization) to its correct path: https://developers.vtex.com/docs/guides/vtex-io-documentation-enabling-order-form-optimization. However, currently, the documentation page is rendering incorrectly with the path "/404/docs/recipes/store-management/enabling-order-form-optimization". This pull request aims to fix the redirect so the documentation page is correctly redirected to its intended path.
Reference: #379 
🔗 [Preview](https://deploy-preview-380--elated-hoover-5c29bf.netlify.app/404/docs/recipes/store-management/enabling-order-form-optimization)
> Chore: fix Order Form redirect 

- src/pages/api/preview.ts
To add a redirect to the login page when a non-authenticated user tries to access the API preview endpoint.
When a non-authenticated user tries to reach the API preview endpoint, they only get an error telling them they're not authenticated, but no means to actually authenticate.
This can only be tested locally or in production. Try pulling this branch to your local copy of this repository, setting the `BUILD_ENV` envinronment variable to `dev` in your `.env.local` file and trying to access the `/api/preview?branch=main` endpoint. If you are not authenticated, it should redirect you to the login page and then back to the home page with a warning at the top (telling you are using the portal in the preview mode).
> Preview API Endpoint Auth

- netlify.toml
Creating a redirect from https://developers.vtex.com/docs/api-reference/catalog-api-seller-portal-overview to https://developers.vtex.com/docs/api-reference/catalog-api-seller-portal
[EDU-10264](https://vtex-dev.atlassian.net/browse/EDU-10264) Feedback #3133 - Error
> docs: create redirect catalog api seller portal

- src/components/search-card/index.tsx
To make the full description of the search cards hidden by default.
Users of the Developers Portal have shown preference to have the search cards hide the full description by default and only show it when requested.
Open the deploy preview and try searching for something. Go through the results and look for the ones with an eye icon by the right side. Make sure it is crossed (off) by default. Try clicking it and make sure the full description of the card now shows.
> Hide search card full description

- next-sitemap.config.js
- src/pages/docs/guides/[slug].tsx
Remove Guides pages with `noindex` meta tag from the sitemap. (Prevent Algolia indexing)
Go to [frontmatter](https://deploy-preview-434--elated-hoover-5c29bf.netlify.app/sitemap-0.xml) and check if the path from any page with:
- `hidden: true` in frontmatter
- `sectionSelected` empty (it isn't in navigation.json)
https://github.com/vtexdocs/devportal/assets/42784961/7abe87e7-a105-4cf0-8364-1290f56c49a2
> fix(sitemap): remove guides page with noindex from sitemap

- src/components/sidebar-section/index.tsx
Fix the sidebar filter in the API Reference section. (The input filter was overlapping the 'filter by method')
Go to the preview page and check if both filters work together and separately.
https://github.com/vtexdocs/devportal/assets/42784961/34dc31f3-1221-4517-81ec-7a806004fc84
> fix(sidebar): fix endpoint filter in api reference

- public/navigation.json
Since the changes in the [Headless CMS API doc](https://developers.vtex.com/docs/api-reference/headless-cms-api#overview) (more info in the [943 PR)](https://github.com/vtex/openapi-schemas/pull/943), the paths for each documentation endpoint are not matching the updates and are currently not rendering the content in the Dev Portal. This PR is to fix this issue.
The path for each endpoint page should contain `projectId` and not `builderId`.
Example: `https://deploy-preview-457--elated-hoover-5c29bf.netlify.app/docs/api-reference/headless-cms-api#get-/_v/cms/api/-projectId-/`
[Preview example](https://deploy-preview-457--elated-hoover-5c29bf.netlify.app/docs/api-reference/headless-cms-api#get-/_v/cms/api/-projectId-/)
> Fix: Headless CMS endpoint path

- src/pages/editor/openapi-preview.tsx
- src/styles/openapi-preview.ts
Add an open API preview feature to create a link preview for PRs in openapi-schemas repository.
The absence of an open API preview 
Using these URL query params:
`/editor/openapi-preview?branch=${branch}&file=${file.json}`
We can define the respective branch and file to be previewed.
For example:
[https://deploy-preview-464--elated-hoover-5c29bf.netlify.app/editor/openapi-preview?branch=master&file=VTEX - Catalog API.json](https://deploy-preview-464--elated-hoover-5c29bf.netlify.app/editor/openapi-preview?branch=master&file=VTEX%20-%20Catalog%20API.json)
> feat(api-reference): openapi preview

- netlify.toml
Creating two redirects.
Broken links.
> Create redirect after removing beta mention in slug

- public/navigation.json
> [EDU-11185] Fixed error URL

- src/components/last-updates-section/index.tsx
- src/pages/updates/release-notes/[slug].tsx
- src/utils/getDocsPaths.ts
Stop rendering Release Notes using the `docs/guides` route.
> fix(getdocspaths): do not fetch docs/release-notes paths for guides

- netlify.toml
This PR redirects the following docs:
-  path `/docs/guides/vtexbr-buybox-context` to the right one: `/docs/apps/vtexbr.buybox-context`. Reference: [EDU-9549](https://vtex-dev.atlassian.net/browse/EDU-9549)
- path `/404/docs/recipes/style/using-css-handles-for-store-customization` to the right one: `/docs/guides/vtex-io-documentation-using-css-handles-for-store-customization`.
Reference: [EDU-9923](https://vtex-dev.atlassian.net/browse/EDU-9923)
> Update netlify.toml: Fixing docs redirects

- src/pages/docs/apps/[slug]/[child].tsx
- src/pages/docs/apps/[slug]/index.tsx
Altered specifiedVersion to treat the following scenarios:
- Specified version without one or two `.0`: now appending `.0` when applicable before comparing to the current version (as reported in [EDU-11202](https://vtex-dev.atlassian.net/browse/EDU-11202))
- Specified version ends in `.`: now appending `0` when applicable before comparing to the current version.
> fix(apps): edit specifiedVersion checks

- netlify.toml
[This link](https://developers.vtex.com/docs/guides/faststore/docs-brandless) is broken, and it's showing in Google search results.
> Fix: create Faststore doc redirect

- public/navigation.json
It is related to the [#1043](https://github.com/vtexdocs/dev-portal-content/pull/1043)
This PR also adds the reference in the navigation to the [Widgets documentation](https://developers.vtex.com/docs/guides/faststore/headless-cms-widgets).
> Update navigation.json: New doc - Mutiple page templates

- netlify.toml
Redirect from `/docs/guides/using-the-docs-builder-to-publish-app-documentation` to `/docs/guides/vtex-io-documentation-docs-builder`.
> Doc: Create redirect

- src/pages/api/openapi/[slug].tsx
- src/utils/getReferencePaths.ts
The Recurrence v1 API is deprecated and will be removed from openapi-schemas. There are no files registered in navigations, for the API was never published.
> Remove recurrence v1 api

- netlify.toml
- public/navigation.json
- Excluded `routes` from sidebar
- Updated `routing` as a markdown doc
- Created redirect from `/docs/guides/vtex-io-documentation-routes` to `/docs/guides/store-framework-routing`
Refers to [#1371](https://github.com/vtexdocs/dev-portal-content/pull/1371)
> docs(navigation.json): routing category cover

- public/navigation.json
adding new endpoint Get orders by order group ID to navigation
Adding to navigation the new endpoint Get orders by order group ID.
> Adding to navigation new endpoint Get orders by order group ID

- netlify.toml
- public/navigation.json
Redirecting the[ troubleshooting](https://developers.vtex.com/docs/guides/faststore/api-extensions-troubleshooting) to its new page and category: https://developers.vtex.com/docs/troubleshooting/issues-during-extending-the-faststore-api-schema
> Fix: redirecting API extensions troubleshooting doc

- public/navigation.json
- src/components/last-updates-section/index.tsx
> EDU-13931: Update navigation.json for new release note

- public/navigation.json
[EDU-14127](https://vtex-dev.atlassian.net/browse/EDU-14127)
> docs(navigation): add ad network integration endpoints

- src/pages/api/openapi/[slug].tsx
- src/utils/getReferencePaths.ts
Replace jsDelivr URLs with internal API routes for better performance and reliability
> refactor(api): update getReferencePaths to use internal API routes

- src/pages/api/openapi/[slug].tsx
- src/pages/docs/api-reference/[slug].tsx
This PR addresses issues with OpenAPI specification reference resolution in the API reference documentation pages.
- Enhanced server-side reference resolution using SwaggerParser.bundle() for better handling of external references
- Improved client-side fallback mechanism when server-side resolution fails
- Fixed RapiDoc component configuration to prevent null reference errors
- Added proper development environment support with localhost URLs
- Simplified error handling by consistently returning 404 for unparseable API specs
- Removed special case handling for problematic API specs for better maintainability
These changes make the API reference documentation more reliable and resilient when displaying complex OpenAPI specifications with external references.
> Fix OpenAPI spec reference resolution in API reference documentation

- netlify.toml
Fix origin's URL. Refers to [EDU-11170](https://vtex-dev.atlassian.net/browse/EDU-11170).
> EDU-11170 - Fix origin's URL
