src/components/see-also-section/styles.ts
src/styles/documentation-page.ts
yarn.lock

Fix the margin on mobile screens (documentation page)
Between the first two breakpoints (360-640), the margin was wrong, and the document content size wasn't following the screen size. The margin until `639px` will be `18px` and the content will expand to both sides.
Go to [this page](https://deploy-preview-52--elated-hoover-5c29bf.netlify.app/docs/api-guides/clients) and check if the behavior explained above works.
| before | after |
| -------- | ------ |
|![image](https://user-images.githubusercontent.com/42784961/176454276-c6429928-5958-421c-9749-6e10ad74d2cd.png)|![image](https://user-images.githubusercontent.com/42784961/176454465-86f0a883-30a1-4c14-8cf2-f61e9e6270ad.png)|

fix(documentation-page): page margin in mobile screen

---

package.json
yarn.lock

fix(package.json): updates confliting packages

---

package.json

Update the RapiDoc version.
FIxing the rapidoc version in the file package.json
Check if the [preview](https://deploy-preview-101--elated-hoover-5c29bf.netlify.app/docs/api-reference/catalog) shows the rendered magic blocks as expected.

build(rapidoc): update rapidoc version

---

next.config.js

we should be using cached requests to our navigation files

perf(config): use s3 cdn

---

src/components/sidebar-elements/index.tsx
src/components/sidebar/index.tsx

fix(sidebar-elements): use href

---

package.json

Update the RapiDoc version. [Corresponding RapiDoc PR](https://github.com/vtexdocs/RapiDoc/pull/13)
Removes buttons that are not functional, removes the href from the breadcrumbs and increases the size of the base URL component.
Open the preview deploy and check the API Reference page is similar to the screenshot.

build(package): update rapidoc version

---

src/components/breadcrumb/index.tsx
src/components/breadcrumb/styles.ts
src/pages/docs/api-guides/[slug].tsx

Adiciona breadcrumb nos guias
Figma do projeto inclui breadcrumb nos guias
Acessar um guia e verificar o breadcrumb acima do título da doc

feat(breadcrumb): add breadcrumb component to api-guides

---

src/components/sidebar-elements/index.tsx

feat(sidebar): correct href generation

---

src/components/icons/legacy-cms-icon.tsx
src/messages/language.json
src/pages/docs/legacy-cms/index.tsx
src/utils/constants.ts
src/utils/typings/unionTypes.ts

docs(pages/docs/legacy-cms): add Legacy CMS page

---

src/pages/docs/guides/[slug].tsx
src/pages/updates/release-notes/[slug].tsx
src/utils/getDocsList.preval.ts
src/utils/getDocsPaths.ts
src/utils/getReleasePaths.ts

use `main` branch instead of `readme-docs`

chore(pages): use main branch from dev-portal-content

---

src/components/announcement-bar/IconClose.tsx
src/components/announcement-bar/index.tsx
src/components/announcement-bar/styles.ts
src/components/header/index.tsx
src/components/header/styles.ts
src/styles/documentation-page.ts

feat(announcement-bar): feat announcement bar

---

src/components/release-note/index.tsx
src/components/release-section/index.tsx
src/pages/updates/release-notes/[slug].tsx
src/pages/updates/release-notes/index.tsx
src/styles/documentation-page.ts
src/utils/constants.ts
src/utils/getReleasesData.ts

feat(release-notes): feat release notes page

---

.gitignore
getPEM.sh
netlify.toml
next.config.js
package.json
src/utils/config.ts
yarn.lock

feat(netlify.toml): add file

---

next.config.js
public/navigation.json

feat(navigation): navigation.json comes from public folder

---

next.config.js

fix(config): increse max page data size warning

---

src/pages/api/openapi/[slug].tsx
src/pages/docs/api-reference/[slug].tsx

feat(references): use edge api to get openapis

---

src/utils/getReleasesData.ts

fix the build error
the getReleasesData function was following the wrong branch

fix(utils): fix getReleaseData

---

.gitignore
src/pages/updates/release-notes/[slug].tsx

feat(releases): release notes now are built on demand

---

public/navigation.json

Adding the [Create a Brand](https://developers.vtex.com/docs/guides/create-a-brand) guide to lateral navigation.

fix: add create-a-brand to navigation.json

---

src/components/see-also-section/functions.ts

fix(see-also-section): update functions

---

public/navigation.json
src/components/sidebar-elements/index.tsx
src/components/sidebar/index.tsx
src/pages/docs/guides/[slug].tsx
src/pages/docs/guides/index.tsx

Abrir a sidebar na posição correta

fix(sidebar): open proper sidebar on refresh

---

package.json
src/styles/rapidoc.css

style(rapidoc): update rapidoc version

---

package.json
src/styles/rapidoc.css

style(package.json): update rapidoc version

---

public/navigation.json

Corrigir slugs do navigation.json

chore(navigation.json): fix slugs

---

package.json
public/navigation.json
src/pages/docs/api-reference/[slug].tsx
src/styles/rapidoc.css

Update rapidoc version and styles.
Update API Reference header.

fix(slug): update header and rapidoc version

---

next.config.js

Redirect of Payment Provider Protocol API Overview
Redirect of a 404 URL to a valid one

Redirect of Payment Provider Protocol API Overview

---

public/navigation.json
src/components/last-updates-section/index.tsx
src/pages/docs/api-reference/[slug].tsx
src/styles/global.css

Add API reference title and add styles for HTML table

fix(slug): add api header title

---

public/navigation.json

Include navigation fulfillment and subscriptions

---

next.config.js
public/navigation.json

Chore: Update redirects ad navigation file

chore(navigation): update redirects and navigation

---

public/navigation.json

chore(navigation): update navigation

---

public/navigation.json

Add "Cart Attachments" and "Configuration" Sections to sidebar
Include "Cart Attachments" and "Configuration" Dev Guide endpoints reference

Added "Cart Attachments" and "Configuration" Sections to sidebar

---

src/components/breadcrumb/styles.ts
src/components/markdown-renderer/components.tsx
src/components/markdown-renderer/styles.module.css
src/components/overview-card/index.tsx
src/components/whats-next-card/index.tsx
src/components/whats-next-card/styles.ts
src/pages/docs/api-reference/index.tsx
src/pages/docs/storefront-development/index.tsx
src/pages/docs/vtex-io-apps/index.tsx
src/styles/documentation-page.ts
src/styles/global.css
src/utils/constants.ts
src/utils/typings/types.ts

Export OverviewCard component to MDXRemote

feat(components): export overviewcard and update table styles

---

public/navigation.json

docs: adding navigation release note api breaking change

---

algolia/scraper_md.json
algolia/scraper_openapi.json
algolia/scripts/scraper.sh

Update config files to scrape reference pages.

feat(scraper): update scraper config files

---

public/navigation.json

docs(public/navigation.json): adding SafeData release note to navigation

---

src/utils/getReferencePaths.ts

Correcting reference path map for the Orders API (PII version)

---

next.config.js

Migrating some redirects from readme and adding new ones related to PII docs.
This was tested locally and is working ok.

Redirects new and migrated.

---

.github/workflows/release-version.yml

fix(release-version): add token to checkout action

---

next.config.js

fix(config): stop worker threads

---

public/navigation.json

Edit Marketplace API navigation according to PR [#733](https://github.com/vtex/openapi-schemas/pull/733)

docs(navigation): edit marketplace api paths

---

public/navigation.json

Fix Marketplace API navigation.

docs(navigation): fix marketplace api navigation

---

src/components/last-updates-section/index.tsx

chore(last-updates-section): update hard-coded lastReleaseNote

---

public/navigation.json
src/pages/api/openapi/[slug].tsx
src/utils/getReferencePaths.ts
yarn.lock

Fixing Marketplace API navigation.

docs(navigation): correct marketplace api navigation

---

package.json
src/components/code-block/index.tsx
src/components/code-block/styles.ts
src/components/copy-button/index.tsx
src/components/copy-button/styles.ts
src/components/markdown-renderer/components.tsx
src/components/markdown-renderer/styles.module.css
src/styles/global.css

Adiciona botão para copiar o código de um snippet
Acessar uma doc com bloco de código e clicar no ícone de copiar código
https://user-images.githubusercontent.com/60782333/215915867-07889a33-5864-46e6-97c8-b9fbe332c47b.mov

feat(markdown-renderer): add CodeBlock and CopyButton components

---

public/navigation.json

Adding subscriptions v2 to navigation bar of API reference

Adding subscriptions v2 to navigation

---

public/navigation.json

fix navigation subscriptions v2

---

public/navigation.json
src/components/announcement-bar/index.tsx
src/components/announcement-bar/styles.ts
src/components/article-pagination/index.tsx
src/components/article-pagination/styles.ts
src/components/breadcrumb/styles.ts
src/components/markdown-renderer/components.tsx
src/components/markdown-renderer/styles.module.css
src/components/whats-next-card/styles.ts
src/pages/docs/guides/[slug].tsx
src/styles/documentation-page.ts

Fix color contrast issues, handle article pagination styles issues, move jsonpath functions to getStaticProps

fix(article-pagination): fix styles and other accessibility issues

---

src/components/sidebar-elements/styles.ts
src/pages/updates/release-notes/[slug].tsx

style(sidebar-elements): fix maxwidth

---

src/components/layout.tsx
src/components/sidebar/index.tsx
src/pages/404.tsx
src/pages/500.tsx
src/pages/_app.tsx
src/pages/docs/api-reference/[slug].tsx
src/pages/docs/guides/[slug].tsx
src/pages/index.tsx
src/pages/updates/release-notes/[slug].tsx
src/utils/contexts/sidebar.tsx
src/utils/navigation-utils.ts
src/utils/typings/types.ts

refactor(sidebar): rewrite sidebar functions

---

package.json
src/pages/docs/api-reference/[slug].tsx

Sync the fork with the original repository.
Open the preview and check if it looks and works the same way as before.

chore: sync rapidoc fork

---

next.config.js

Create a redirect to the Checkout overview page.
From: https://developers.vtex.com/docs/api-reference/checkout-api-overview
To: https://developers.vtex.com/docs/api-reference/checkout-api-overview

Create redirect - Checkout overview

---

src/pages/docs/apps/[slug].tsx
src/pages/docs/apps/[slug]/[child].tsx
src/pages/docs/apps/[slug]/index.tsx
src/styles/apps-page.ts
src/utils/getAppReadme.ts
src/utils/getChildDocApp.ts

feat(apps): fetches vtex io apps documentation

---

src/components/markdown-renderer/components.tsx
src/styles/global.css

style(styles): update table font-size

---

public/navigation.json

release note about custom io app breaking change

docs: adding new release note to navigation

---

public/navigation.json

This pull request aims to add the Kit Look App release note to the navigation.

chore(navigation): add kit look app release note to navigation.json

---

src/components/breadcrumb/styles.ts
src/components/code-block/styles.ts
src/components/markdown-renderer/styles.module.css
src/styles/documentation-page.ts
src/styles/global.css

style(styles): update styles considering the figma file

---

public/navigation.json

Correct path logistics endpoints
changed endpoints' paths

Correct path logistics endpoints

---

public/navigation.json

Add "Create a regular order from an existing cart" article reference to sidebar

Add "Create a regular order from an existing cart" reference to sidebar

---

src/components/layout.tsx

feat(header scripts): add GA script

---

next.config.js
public/navigation.json

This PR implements changes needed because of the slug change of the `Making your first request` guide:
- Create redirect
- Fix navigation slug

Navigation and redirect/making your first request/update

---

public/navigation.json

Edit Catalog, Search and Message Center guides organization on sidebar.

docs(navigation): edit Catalog, Search and Message Center guides

---

src/components/layout.tsx

feat(layout): correct GTM

---

next.config.js
public/navigation.json

Adjust navigation and redirects according to improvements in authentication content architecture in getting started section.

Getting started authentication navigation improvements

---

next.config.js
public/navigation.json

Removing unused guides from navigation after merging content with other guides in [#254](https://github.com/vtexdocs/dev-portal-content/pull/254).

docs(navigation): update catalog guides navigation

---

next.config.js
public/navigation.json

The path param was incorrect, instead of "orderId" should be "sellerOrderId", so there was a change on the link and a redirect.

Change path authorize fulfillment

---

public/navigation.json

Update sidebar "Get sellers by region or address"
Update sidebar "Get sellers by region or address"

Update sidebar "Get sellers by region or address"

---

public/navigation.json

Update sidebar "Fulfillment" and "Region"

Update sidebar "Fulfillment" and "Region"

---

public/navigation.json

Updated "Create a new cart" endpoint reference.

Updated "Create a new cart" endpoint reference

---

next.config.js
public/navigation.json

Delete guide on how to activate an SKU and create a redirect.

docs: delete guide and create redirect

---

next.config.js

- [] New feature (non-breaking change which adds functionality)

docs: create redirects marketplace protocol

---

public/navigation.json
yarn.lock

edições no menu de navegação
Improve Dev portal navigation
Improve the organization

docs(navigation): improve pricing guides on navigation.json

---

next.config.js

redirect 2

---

public/navigation.json

Adding three new Intelligent Search guides to Dev Portal navigation.

docs(navigation): add new intelligent search guides

---

public/navigation.json

PR created to add PSE Payment Method reference to the Payment Integration Guide sidebar.

Add PSE Payment Method - Payment Integration Guide

---

public/navigation.json

PR created to update Release Note position (sidebar) - PSE: Payment method

Update Release Note position - PSE: Payment method

---

src/components/header/index.tsx

Updating topbar content to launch persona research form

Top bar update: persona research

---

package.json
src/components/JsonEditorComponent/index.tsx
src/components/JsonEditorComponent/styles.ts

feat(editor): add toast feedback to json editor

---

public/navigation.json

Fix category of Catalog guide in navigation.

docs(navigation): fix position of catalog guide

---

tsconfig.json

fix(tsconfig): who would've guessed tsconfig can get this hard

---

netlify.toml

New redirect created (EDU-9504).
From: https://developers.vtex.com/docs/guides/how-to-add-and-handle-custom-information-in-the-order
To: https://developers.vtex.com/docs/guides/add-and-handle-custom-information-in-the-order

New redirect  Add & handle custom inf in the order

---

.github/workflows/cypress.yml
cypress.config.mjs
src/tests/cypress/integration/api-reference.cy.js
src/tests/cypress/integration/documentation-pages-status.cy.js
src/tests/cypress/plugins/index.mjs
src/tests/cypress/support/index.js
src/tests/summary-report.js

To improve the Cypress GitHub action to make it create a comment with a summary of the tests results.
The output of the tests is currently hidden and somewhat cryptic.
Check the output of the Cypress GitHub action and make sure the reported errors show up in a comment in this PR.

Feat/Tests Summary Report

---

package.json
src/styles/rapidoc.css

Update rapidoc version [PR 28](https://github.com/vtexdocs/RapiDoc/pull/28)

style(rapidoc): update rapidoc version and styles

---

public/navigation.json

Reorganizing Catalog API reference lateral navigation.

docs(navigation): update catalog api menu

---

public/navigation.json

PR created to add new endpoint "Handle Cart Items" and sidebar reorganization.

Add new endpoint "Handle Cart Items" and sidebar reorganization

---

src/pages/docs/api-reference/[slug].tsx
src/pages/docs/apps/[slug]/[child].tsx
src/pages/docs/guides/[slug].tsx
src/pages/updates/release-notes/[slug].tsx
src/utils/typings/unionTypes.ts

Update searchable attributes that will be used in search page
- doctitle: guides/reference/updates
- doccategory: reference
- method: reference
- actiontype: updates

feat(pages): update searchable attributes

---

netlify.toml
public/navigation.json

Update redirects and navigation in order to viabilize this PR (https://github.com/vtexdocs/dev-portal-content/pull/350) that updates english content within the portal.
Set right routes to the files according to their new slugs.
Tests on the sidebar tool (https://developers.vtex.com/editor/sidebar)
- [X ] Requires change to documentation, which has been updated accordingly.

docs: fixing redirects and navigations according to KR 23Q2-KR1

---

public/navigation.json

PR created to add "Checkout error codes" guide to the sidebar

Add Checkout error codes guide to the sidebar

---

netlify.toml
public/navigation.json

Use `apps` route in the sidebar

chore(navigation.json): update vtex io apps sidebar

---

src/pages/docs/guides/[slug].tsx

fix(guides): fix activeslug

---

public/navigation.json

chore(navigation.json): remove beta label from faststore link

---

public/navigation.json

It relates to task [LOC-10439](https://vtex-dev.atlassian.net/browse/LOC-10439) and it updates a file title in order to reflect the updates made by the Localization team on this same file.

updated file title on navigation.json

---

package.json
src/components/markdown-renderer/index.tsx
yarn.lock

Eliminate render-blocking resources

perf(markdown-renderer): remove highlightjs import using head link

---

public/navigation.json

chore(navigation.json): fixes navigation slugs

---

public/navigation.json

It relates to task [LOC-10431](https://vtex-dev.atlassian.net/browse/LOC-10431) and PR[dev-portal-content-396](https://github.com/vtexdocs/dev-portal-content/pull/396). Updates the title of a file in order for it to reflect the fixes made by the Localization team.

updated a file title on navigation.json

---

src/components/sidebar/index.tsx
src/utils/navigation-utils.ts

The sidebar is not working correctly for API references that use multiple specs in the same category.
https://developers.vtex.com/docs/api-reference/marketplace-apis
https://developers.vtex.com/docs/api-reference/marketplace-protocol

feat(sidebar): support different openapi specs in the same category

---

public/navigation.json

Sidebar updated to remove information of List Payment Methods endpoint (EDU-9483).

Updated sidebar: Deprecation of List Payment Methods endpoint

---

netlify.toml

Created new redirect (List Payment Methods > List Payment Provider Manifest)

List Payment Provider Manifest endpoint redirect

---

public/navigation.json
src/components/last-updates-section/index.tsx

Add the May category and release notes about the new GTM app version.
Add the new release note for the Google Tag Manager app, [created on this other PR](https://github.com/vtexdocs/dev-portal-content/pull/421).

Update sidebar: New Release Note for Google Tag Manager

---

src/components/feedback-section/index.tsx
src/components/search-input/results-box.tsx
src/components/sidebar-section/index.tsx
src/components/tooltip/index.tsx
src/pages/docs/api-reference/[slug].tsx
src/pages/docs/apps/[slug]/[child].tsx
src/pages/docs/apps/[slug]/index.tsx
src/pages/docs/guides/[slug].tsx

- Remove unnecessary rerenders following the new React docs [(You Might Not Need an Effect)](https://react.dev/learn/you-might-not-need-an-effect)
Compare the lighthouse report for the preview page with the production version.

perf: code optimization

---

netlify.toml

chore(netlify.toml): add redirect for livestreaming app

---

netlify.toml

This PR redirects https://vtex.io/docs/recipes/store-management/enabling-order-form-optimization to https://developers.vtex.com/docs/guides/vtex-io-documentation-enabling-order-form-optimization

Chore: redirect Order Form doc

---

src/components/article-pagination/index.tsx
src/components/article-pagination/styles.ts
src/components/markdown-renderer/styles.module.css
src/components/method-category/index.tsx
src/components/overview-card/styles.ts
src/pages/docs/api-reference/[slug].tsx
src/styles/rapidoc.css
src/utils/navigation-utils.ts

| Before | After | Description|
|-------|-------|------------|
|![](https://github.com/vtexdocs/devportal/assets/60782333/80507a09-2b6f-4606-afef-56a66c888364) |![](https://github.com/vtexdocs/devportal/assets/60782333/7f0c8a0f-b3e2-4cd8-b7c2-a4b1a71a1ba7) | Head title according to API endpoint.
| | ![](https://github.com/vtexdocs/devportal/assets/60782333/c498a857-44f6-47b3-9422-704786dade8a)| API pagination
**RapiDoc updates** - [#PR 33](https://github.com/vtexdocs/RapiDoc/pull/33)
| Before | After | Description|
|-------|-------|------------|
| ![](https://github.com/vtexdocs/devportal/assets/60782333/ad99339d-aa6e-42d2-bb2e-2f20f6ac5097)| ![](https://github.com/vtexdocs/devportal/assets/60782333/d2a39219-f332-4edd-b899-5d806a4453d9)| Comprehensive breadcrumbs …

feat(api-references): add api pagination and other minor improv

---

src/tests/cypress/integration/api-guides.cy.js
src/tests/cypress/integration/api-reference.cy.js

To make the Table of Contents test more precise and fast to prevent errors.

test(cypress): simplify the test on TOC in guides pages

---

public/navigation.json
src/components/last-updates-section/index.tsx

Update sidebar: New Release Note for Extensions Hub

---

public/navigation.json

Adding troubleshooting guide to navigation

docs(navigation): add troubleshooting category and first guide

---

public/navigation.json

feat : adding new endpoint
add document to developers side navigation

EDU-9476 New endpoint Get matcher information settings

---

public/navigation.json

Adding Search promotion by name endpoint of Promotions API to sidebar navigation.

docs(navigation): add promotions api endpoint

---

public/navigation.json

Update navigation to new Sales App

---

public/navigation.json

Adding three release notes to navigation:
- https://developers.vtex.com/updates/release-notes/2023-07-05-recaptcha-validation-will-now-follow-orderform-configuration-for-all-requests
- https://developers.vtex.com/updates/release-notes/anti-fraud-flow-for-debit-card-transactions
- https://developers.vtex.com/updates/release-notes/2023-06-28-recaptcha-v3-support-available-for-integrations

docs(navigation): added jun/jul 2023 releases

---

src/pages/api/openapi/[slug].tsx
src/utils/getReferencePaths.ts

Adding a new API (keeping it out of navigation for now).

docs: add intelligent search events api headless

---

public/navigation.json

Navegation bar updated to include the following references: 
- Release Notes: Anti-fraud flow for debit card transactions and reCAPTCHA validation will now follow orderForm configuration for all requests
- Article reference: Implementing a pre-analysis anti-fraud flow for debit card transactions
- Article reference: Google Pay: processing information for payment providers and anti-fraud
Create reference links.

Navigation bar updated

---

CHANGELOG.md
netlify.toml

It relates to task [LOC-10873](https://vtex-dev.atlassian.net/browse/LOC-10873), [This PR](https://github.com/vtex-apps/product-price/pull/122) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).

Fixed redirect for product-price app

---

public/navigation.json

add teasers field release notes to navigation

docs(navigation): add teasers field release notes to navigation

---

public/navigation.json

Adding Change in the SKU notification behavior release notes to navigation.

docs(navigation): add change in sku notification release notes

---

public/navigation.json

Add builders application form RN to navigation

---

netlify.toml

docs: add redirect

---

public/navigation.json

docs(navigation): edit promotions api

---

public/navigation.json

Inclusion of marketplace guide in side navigation menu.

EDU-7868 | Navigation marketplace guide

---

public/navigation.json

docs(navigation): update erp guide name in nav

---

src/styles/documentation-page.ts

style(documentation-page): update content width

---

public/navigation.json
src/components/last-updates-section/index.tsx

chore(navigation): updates navigation.json

---

netlify.toml

Create redirects.
Fix broken links.

Feedback 3088 redirect

---

netlify.toml
public/navigation.json
src/pages/api/openapi/[slug].tsx
src/pages/api/postman/[slug].tsx
src/utils/getReferencePaths.ts

docs: edit-legacy-cms-portal-nav

---

src/pages/docs/api-reference/index.tsx

docs: update index.tsx

---

public/navigation.json

This PR updated navigation.json to add a new release note for Headless CMS. For more information about it, refer to this other PR: https://github.com/vtexdocs/dev-portal-content/pull/618

Update navigation.json: New release notes

---

public/navigation.json

docs(navigation): edit master data api v2

---

netlify.toml
src/components/last-updates-section/index.tsx

chore(netlify.toml): update redirects and lastrelease

---

public/navigation.json

Removing export order report because the endpoints were removed.

docs(remove file from navigation): removing export order report

---

netlify.toml

docs(redirect): redirects

---

public/navigation.json

docs(navigation): update authentication guides

---

netlify.toml

docs: update netlify.toml

---

public/navigation.json

docs(navigation): add vtex id endpoints

---

public/navigation.json

docs(navigation): fix vtex id endpoint path

---

public/navigation.json

Changes MOI nested doc's title from `API Integration` to:
```
"name": "Multilevel omnichannel inventory API integration",
"slug": "multilevel-omnichannel-inventory-api-integration",
```                  
provide more context to article

docs(changes doc title): adds more context to this doc's title

---

src/utils/mermaidInit.ts

Updates mermaid styles
See
- /docs/guides/vtex-io-documentation-performing-ab-testing-between-legacy-and-io
- /docs/guides/data-residency
- /docs/guides/vtex-io-multi-language-stores
| Before | After |
| ------- | ----- |

style(mermaidinit.ts): update mermaid theme

---

netlify.toml

docs: create pii doc redirect

---

src/pages/api/openapi/[slug].tsx
src/utils/getReferencePaths.ts

docs: add user data rights api

---

src/components/last-updates-section/index.tsx

This PR updates the **Last Updates** section with the new release note.

Docs: update the `last-update-section` component to reflect the new release note

---

src/styles/global.css

Improve details/summary styles
|Before|After|
|-------|----|
|![](https://github.com/vtexdocs/devportal/assets/60782333/12cc6319-d25b-4041-8d70-4aef028dee7a)|![](https://github.com/vtexdocs/devportal/assets/60782333/cac4b2db-ea68-4d97-9bb8-9b4e20eb0473)

style(global.css): update details and summary styles

---

public/navigation.json

chore(navigation): update sidebar

---

public/container-template.json

This PR adds new Google Tag Manager container information created by Raquel Tótora.
Preview: https://deploy-preview-488--elated-hoover-5c29bf.netlify.app/container-template.json

Docs: fix GTM container

---

public/navigation.json

chore(navigation): improving clients docs

---

netlify.toml

Create redirects.
Broken links.

Redirect lead time beta to help center

---

public/navigation.json

Adding a License Manager API endpoint to navigation.

docs(navigation): add LM api delete user

---

netlify.toml
public/navigation.json

docs: authentication guides nav and redirects

---

public/navigation.json

Release note: Update navigation.json

---

public/navigation.json
src/components/last-updates-section/index.tsx

Related to: https://github.com/vtexdocs/dev-portal-content/pull/767

EDU-10892 - Update navigation.json

---

public/navigation.json

docs(navigation): add intelligent search api

---

public/navigation.json

docs(navigation): update master data v1 title

---

netlify.toml

<docs>: <link redirect>
<! redirect from this link: https://developers.vtex.com/vtex-rest-api/reference/updateseller, to this link: https://developers.vtex.com/docs/api-reference/marketplace-apis#patch-/seller-register/pvt/sellers/-sellerId- >

EDU-11017 - redirect link seller update by seller ID

---

src/tests/cypress/integration/api-reference.cy.js
src/tests/cypress/integration/documentation-pages-status.cy.js

add additional `wait` to prevent delay erros

test(api-reference): add additional wait to tests in reference page

---

public/navigation.json

chore(navigation.json): add release note to navigation

---

public/navigation.json

chore(navigation.json): update api guides navigation

---

netlify.toml

docs: create redirect

---

netlify.toml
src/pages/api/openapi/[slug].tsx
src/utils/getReferencePaths.ts

docs: update Data Subject Rights API name

---

src/pages/api/openapi/[slug].tsx
src/utils/getReferencePaths.ts

docs: edit api name

---

netlify.toml

docs: create session manager api redirect

---

netlify.toml

docs: edit session manager api redirects

---

public/navigation.json

Fixed Link

---

public/navigation.json

Adding services guides (https://github.com/vtexdocs/dev-portal-content/pull/762) to navigation.

docs(navigation): add services course

---

public/navigation.json

The links for each endpoint in the Reviews and Ratings API are broken. This PR aims to fix it. Related issue: https://github.com/vtex/openapi-schemas/pull/1107

Fix: Reviews and Ratings API navbar links

---

netlify.toml

Redirecting:
- "/vtex-rest-api/reference/using-postman" > [Making your first request](https://developers.vtex.com/docs/guides/making-your-first-request)
- "/docs/api-reference/get-to-know-vtex-apis" > [API Reference](https://developers.vtex.com/docs/api-reference)

Redirect dev portal legacy pages

---

src/pages/docs/guides/faststore/[slug].tsx
src/pages/docs/guides/faststore/index.tsx

fix(faststore/[slug].tsx): allows listing faststore docs

---

src/components/faststore-components/Accordion/UsageAccordion.tsx
src/components/faststore-components/Accordion/UsageAccordionMultiple.tsx
src/components/faststore-components/CardList/CardItem.tsx
src/components/faststore-components/CardList/CardList.tsx
src/components/faststore-components/CardList/card-list.module.css
src/components/faststore-components/Carousel/CarouselSimpleUsage.tsx
src/components/faststore-components/Carousel/carousel-item.module.css
src/components/faststore-components/constants.tsx
src/components/faststore-components/index.ts

chore(faststore-componentes): update faststore components and constants

---

public/container-template.json

This PR fixes this container available for Goog Tag Manager (GTM) users to download.
Previously, the script located in the `value` field at line `1749` would display a random message on stores implementing GTM. The current fix ensures that this message no longer appears while retaining the script within the container. This script enhances the data collected within the data layer by providing additional information related to promotions, creative slots, item lists, and more to ecommerce events. The enriched data obtained serves for analytics and other tracking purposes within Google Tag Manager.

Docs: update container-template.json

---

src/components/faststore-components/CardList/card-list.module.css
src/components/faststore-components/SectionItem/SectionItem.tsx
src/components/faststore-components/SectionItem/section-item.module.css
src/components/faststore-components/Tokens/token-table.module.css
src/components/faststore-components/Tokens/typeset.module.css
src/components/faststore-components/markdown-renderer/fastStoreComponents.tsx
src/pages/docs/guides/[slug].tsx
src/pages/docs/guides/faststore/[slug].tsx
src/styles/documentation-page.ts

style(faststore-components): improve faststore content rendering styles

---

package.json
src/components/faststore-components/markdown-renderer/fastStoreComponentsStyle.ts
src/styles/documentation-page.ts

chore(package.json): update components lib version

---

src/pages/docs/guides/faststore/[slug].tsx

Enable the **See Also** section in FastStore guides
Access `/docs/guides/faststore/themes-overview` and check the **See Also** section

feat(faststore/[slug].tsx): enable seeAlso functionality

---

public/navigation.json

Fix: Documentation guidelines slug in navigation.json

---

public/navigation.json

docs(navigation): fix master data api v1 and v2 navigation

---

public/navigation.json

Redefine Store Framework guides navigation as part of [EDU-11191](https://vtex-dev.atlassian.net/browse/EDU-11191)

docs(navigation): edit store framework navigation

---

src/pages/docs/guides/faststore/[slug].tsx
src/utils/getDocsPaths.ts
src/utils/getFastStorePaths.ts

chore(getfaststorepaths): update FastStore docs branch

---

netlify.toml

Redirect:
From [https://developers.vtex.com/docs/guides/how-to-use-and-create-clients-on-vtex-io](https://developers.vtex.com/docs/guides/how-to-use-and-create-clients-on-vtex-io)
To [https://developers.vtex.com/docs/guides/vtex-io-documentation-how-to-create-and-use-clients](https://developers.vtex.com/docs/guides/vtex-io-documentation-how-to-create-and-use-clients)

Update netlify.toml: Fixing doc redirect

---

netlify.toml

Redirecting 404 page to the correct URL

Redirect VTEX Tracking

---

public/navigation.json

[EDU-11006] Removed sidebar B2B setup e Legacy B2B components

---

netlify.toml

chore(netlify.toml): add redirect

---

netlify.toml

chore(netlify.toml): update redirect

---

netlify.toml

creating a redirect for api reference

redirect oms endpoint

---

public/navigation.json

[EDU-11274](https://vtex-dev.atlassian.net/browse/EDU-11274)

docs(navigation): edit intelligent search api

---

netlify.toml

[EDU-11006] Redirect URL B2B setup e Legacy B2B components

---

netlify.toml

docs: create redirect master data api

---

netlify.toml

**Redirect**
From: /docs/guides/vtex-store-sitemap
To: /docs/apps/vtex.store-sitemap

Doc: Updating netlify.toml

---

netlify.toml

Fixing redirect for vtex.store-sitemap

Doc: fixing redirect store sitemap

---

public/navigation.json

Adding a new content in Developer Portal: "Best practices on workspaces management"

Doc: Updating navigation.json

---

public/navigation.json

[EDU-11752] Reactivate sidebar

---

src/components/last-updates-section/index.tsx

chore(last-updates-section): update lastreleasenote

---

netlify.toml

create vtex tracking api redirect

create redirect tracking API

---

netlify.toml

Creating redirects for Logistics, Orders and Pricing API overviews.

docs: create redirects api overviews

---

src/pages/api/openapi/[slug].tsx
src/utils/getReferencePaths.ts

Adding the Checkout Configuration API to Dev Portal, without displaying it in the navigation

feat: add Checkout Config API

---

netlify.toml

chore(netlify.toml): add faststore redirects

---

public/navigation.json
src/components/last-updates-section/index.tsx

This PR adds the new FastStore release note to the sidebar and the Dev Portal home page. 
Reference: https://github.com/vtexdocs/dev-portal-content/pull/1020

Chore: FastStore release note

---

public/navigation.json

related to https://github.com/vtex/openapi-schemas/pull/1160

docs(navigation): update master data apis navigation

---

public/navigation.json

Fix the slug for the [3. Integrating the VTEX Login](https://developers.vtex.com/docs/guides/faststore/go-live-3-integrating-the-vtex-login) doc

Fix: Integrating the VTEX login slug

---

src/components/faststore-components/Newsletter/NewsletterUsage.tsx
src/pages/docs/apps/[slug]/index.tsx

fix(apps/[slug]): parse markdown value from json

---

netlify.toml

Creating redirects to fix 404 error in some URLs.

docs: creating redirects to fix 404 error 

---

public/navigation.json

Fix sidebar link to access [guides/querying-b2b-order-statuses](https://developers.vtex.com/docs/guides/querying-b2b-order-statuses)

[EDU-11754] Fixed sidebar link

---

netlify.toml

chore(netlify.toml): update faststore redirects

---

public/navigation.json

Fix: FastStore navigation.json

---

src/components/last-updates-section/index.tsx
src/pages/docs/apps/[slug]/index.tsx

chore(last-updates-section): update last rn

---

netlify.toml

docs: create redirect master data guide

---

src/pages/docs/apps/[slug]/[child].tsx
src/pages/docs/apps/[slug]/index.tsx
src/utils/constants.ts

fix(apps/slug): do not use replacemagicblocks

---

public/navigation.json

adding six endpoints to navigation related to Change order beta
Adding endpoints do left navigation

adding change order beta to navigation

---

public/navigation.json

changing "Guides" category name from Fulfillment to Logistics.

changing from Fulfillment to Logistics

---

netlify.toml

[EDU-9472](https://vtex-dev.atlassian.net/browse/EDU-9472)

docs: create redirect to safedata app doc

---

public/navigation.json

Adding release notes to navigation.

docs(navigation): add master data v1 release notes

---

public/navigation.json

[EDU-10740] Bulk Import Spreadsheet Sidebar

---

public/navigation.json

[EDU-10740] New sidebar Bulk import

---

src/pages/docs/apps/[slug]/[child].tsx
src/pages/docs/apps/[slug]/index.tsx
src/utils/replaceHTMLBlocks.ts

fix(pages/docs/apps): use replaceHTMLBlocks

---

public/navigation.json
src/pages/api/openapi/[slug].tsx
src/utils/getReferencePaths.ts

EDU 10740 adjusted slug and navigation bar

---

netlify.toml

Creating a redirect to app documentation.
>⚠️ **Merge only after https://github.com/vtex-apps/search-graphql/pull/133**

docs: create redirect search graphql

---

public/navigation.json

docs(navigation): fix sidebar link

---

public/navigation.json

Updating navigation for builders docs.

Updating navigation.json

---

package.json

chore(package.json): update faststore major

---

src/utils/replaceHTMLBlocks.ts

fix(replacehtmlblocks): close open img tags

---

src/utils/replaceHTMLBlocks.ts

fix(replacehtmlblocks): consider <img...></img> case

---

public/navigation.json

Reference: https://github.com/vtexdocs/dev-portal-content/pull/1111

Update navigation.json - Section override v2

---

package.json
src/components/layout.tsx
src/utils/constants.ts
src/utils/typings/types.ts

chore(package.json): update components package

---

src/components/faststore-components/SectionItem/section-item.module.css
src/pages/docs/guides/faststore/[slug].tsx

feat(faststore/[slug].tsx): allow hideTOC frontmatter option

---

src/components/faststore-components/OverviewSection/OverviewSection.tsx
src/components/last-updates-section/index.tsx
src/styles/faststore.scss
src/styles/global.css

style(faststore.scss): update faststore table styles

---

src/components/faststore-components/SectionItem/SectionItem.tsx
src/components/faststore-components/SectionItem/section-item.module.css
src/styles/documentation-page.ts
src/styles/global.css

style(sectionitem): update sectionitem styles

---

package.json
src/styles/apps-page.ts

chore(package.json): update vtexdocs/components version

---

netlify.toml

docs(redirect): data protection plus

---

netlify.toml
public/navigation.json

update navigation and redirects to reflect https://github.com/vtexdocs/dev-portal-content/pull/1161

docs: update redirect and navigation for store framework category

---

public/navigation.json

[EDU-12476](https://vtex-dev.atlassian.net/browse/EDU-12476)

docs(navigation): fix copy sku files endpoint nav

---

public/navigation.json
src/pages/api/openapi/[slug].tsx
src/utils/getReferencePaths.ts

fix: updating pick and pack api

---

netlify.toml

EDU-9997 - Creating redirect vtex.search/banner

---

netlify.toml

docs: remove data-privacy redirect

---

public/navigation.json

Adjusting a Checkout Security subcategory, according to https://github.com/vtexdocs/dev-portal-content/pull/1186

docs(navigation): fix checkout security subcategory

---

public/navigation.json

[EDU-12329](https://vtex-dev.atlassian.net/browse/EDU-12329)

docs(navigation): add data protection plus guides

---

public/navigation.json

Getting started with storefront solutions sidebar

---

public/navigation.json

docs: add VTEX Platform Overview category and docs to navigation | 24H1KR3

---

netlify.toml

docs: create redirect to Composability guide

---

public/navigation.json

Adding vtex platform overview release note to navigation.json

Adding vtex platform overview release note to navigation.json

---

public/navigation.json

Reference: https://github.com/vtexdocs/dev-portal-content/pull/1207

feat(navigation.json): add fs managing performance

---

netlify.toml

[EDU-12580](https://vtex-dev.atlassian.net/browse/EDU-12580)

docs: create redirect to new platform overview category

---

public/navigation.json

Adding configuring-dynamic-routes-in-vtex-io-services.md to sidebar

Adding configuring-dynamic-routes-in-vtex-io-services.md to sidebar

---

public/navigation.json

chore(navigation.json): fix navigation error

---

public/navigation.json

Reference: https://github.com/vtexdocs/dev-portal-content/pull/1195

feat(navigation.json): update faststore overview doc slug

---

public/navigation.json

docs: fix orders pii api navigation

---

public/navigation.json

Preview: https://deploy-preview-684--elated-hoover-5c29bf.netlify.app/docs/guides/faststore/managing-performance-testing-the-server-side-rendering

feat(navigation.json): add fs testing-the-server-side-rendering doc

---

public/navigation.json

fix(navigation.json): troubleshooting sidebar

---

public/navigation.json

adding a new troubleshooting guide to navigation. ref: https://github.com/vtexdocs/dev-portal-content/pull/1230

docs(navigation): add troubleshooting modal layout

---

public/navigation.json

add new logistics api inventory endpoints to navigation

add new endpoints to navigation

---

public/navigation.json

adding to navigation new release note about logistics api endpoints

docs: adding to navigation

---

public/navigation.json

feat(navigation.json): add fs dynamic content

---

public/navigation.json
src/components/last-updates-section/index.tsx

Reference: https://github.com/vtexdocs/dev-portal-content/pull/1238

feat(navigation.json): add dynamic content release note

---

src/pages/docs/app-development/index.tsx

Adding developer experience link 
[EDU-12582](https://vtex-dev.atlassian.net/browse/EDU-12582)

docs: adding dev experience link

---

public/navigation.json

EDU-18812 Fixed sidebar Buyer organizations

---

public/navigation.json

fix(navigation.json): troubleshooting sidebar navigation

---

public/navigation.json
src/messages/language.json
src/pages/docs/troubleshooting/index.tsx
src/utils/constants.ts
src/utils/get-url.tsx
src/utils/typings/types.ts
src/utils/typings/unionTypes.ts

Add a new support component to the troubleshooting page

feat(index.tsx): adding new support component to the troubleshooting page

---

src/components/faststore-components/markdown-renderer/fastStoreComponents.tsx

fix(faststorecomponents.tsx): fix Tabs behavior

---

public/navigation.json

feat(navigation.json): update troubleshooting sidebar

---

public/navigation.json

docs(navigation): fix data protection plus guides

---

public/navigation.json

- Creating new categories to reorganize docs.
- Adding vtex-io-documentation-creating-an-interface-for-your-app-settings to the sidebar.
[EDU-5808](https://vtex-dev.atlassian.net/browse/EDU-5808)

docs: reorganizing and updating navigation.json

---

public/navigation.json

Reference: https://github.com/vtexdocs/dev-portal-content/pull/1229

feat(navigation.json): add new troubleshooting article

---

public/navigation.json

Reference: https://github.com/vtexdocs/dev-portal-content/pull/1264

feat(navigation.json): add section override use cases

---

src/pages/docs/storefront-development/index.tsx

feat(storefront-development/index.tsx): adding dev experience link

---

src/components/last-updates-section/index.tsx

Update the component with the last release note.

feat(last-updates-section): update last-updates-section component

---

public/navigation.json
src/pages/api/openapi/[slug].tsx

VTEX DO endpoints capitalization corrections.

Lateral menu update summary names

---

src/pages/api/postman/[slug].tsx
src/pages/docs/api-reference/index.tsx
src/utils/getReferencePaths.ts

Correct parse error vtex do

---

src/pages/api/postman/[slug].tsx

VTEX DO correct navigation

---

src/pages/api/openapi/[slug].tsx
src/utils/getReferencePaths.ts

Correct get reference paths

---

netlify.toml

redirect - create order tracking

---

public/navigation.json
src/pages/api/openapi/[slug].tsx
src/utils/getReferencePaths.ts

docs: add audience api

---

public/navigation.json
src/pages/api/openapi/[slug].tsx
src/pages/api/postman/[slug].tsx
src/utils/getReferencePaths.ts

- adding VTEX Ad Network API following [these steps](https://developers.vtex.com/docs/api-reference/vtex-ad-network-api#get-/sponsored_products/-facets-)
- relates to https://github.com/vtex/openapi-schemas/pull/1151
- updating postman API mapping

docs: add VTEX Ad Network API

---

public/navigation.json

docs(navigation): fix ad network api

---

public/navigation.json
src/components/last-updates-section/index.tsx

Reference: https://github.com/vtexdocs/dev-portal-content/pull/1288

feat(navigation.json): new release note - troubleshooting guides

---

netlify.toml
public/navigation.json

fix(navigation.json): dynamic content guides

---

public/navigation.json

docs(navigation): add master data v1 guide

---

public/navigation.json

Adding Store Theme doc to sidebar.

docs(navigation.json): Adding Store Theme doc to sidebar

---

public/navigation.json

Reference: https://github.com/vtexdocs/dev-portal-content/pull/1303

docs(navigation.json): add API extensions use cases guides

---

public/navigation.json

Reference: https://github.com/vtexdocs/dev-portal-content/pull/1323

feat(navigation.json): new hCMS content

---

public/navigation.json

fix(navigation.json): scopes guide

---

public/navigation.json

Adding components to navigation.json
[EDU-11381](https://vtex-dev.atlassian.net/browse/EDU-11381)

feat: adding components to navigation.json

---

public/navigation.json

Adding Site Editor docs to sidebar.

docs(navigation.json): updating sidebar

---

public/navigation.json

fix(navigation.json): fixing json

---

public/navigation.json

Reorganizing the [**Store Theme doc**](https://developers.vtex.com/docs/guides/vtex-io-documentation-store-theme) on the sidebar.

docs(navigation.json): reorganizing sidebar

---

public/navigation.json

feat(navigation.json): add the article The Price in the shelf or in the search results is different from the product page

---

public/navigation.json

chore(navigation.json): FastStore release note

---

public/navigation.json

Add PaymentProvider builder guide to navigation

doc(navigation.json): updating sidebar

---

public/navigation.json

Changing title and slug of the **Testing server-side rendering** documentation.

chore(navigation.json): changing title and slug of the Testing server-side rendering doc

---

public/navigation.json

The article title was "PaymentPrvovider Builder"

fix(navigation.json): paymentprovider builder

---

public/navigation.json

Reference: https://github.com/vtexdocs/dev-portal-content/pull/1063

EDU-10899: Update the FastStore API schema sidebar

---

public/navigation.json

Refers to [#1355](https://github.com/vtexdocs/dev-portal-content/pull/1355)

docs(navigation.json): ga4 discrepancy troubleshooting

---

netlify.toml
public/navigation.json

- Update slug in the `navigation.json` file.
- Create redirect in the `netlify.toml` file.
Refers to PR [#1356](https://github.com/vtexdocs/dev-portal-content/pull/1356)

EDU - 10961 - custom page content type

---

public/navigation.json

feat(navigation.json): add new troubleshooting category

---

public/navigation.json

fix(navigation.json): fix Radio Field menu position

---

src/pages/docs/troubleshooting/[slug].tsx
src/utils/getDocsPaths.ts

fix(troubleshooting/[slug].tsx): fix pagination route

---

public/navigation.json
src/components/last-updates-section/index.tsx

feat(navigation.json): EDU-13391 WebOps

---

public/navigation.json

Reference: [1394](https://github.com/vtexdocs/dev-portal-content/pull/1394)

feat(navigation.json): new FastStore release note

---

public/navigation.json

Reference: https://github.com/vtexdocs/dev-portal-content/pull/1391

feat(navigation.json): EDU-13292 Card component

---

public/navigation.json

New subscriptions article about keeping attachments being added to navigation.

Adding new subscriptions guide to navigation

---

public/navigation.json

Add Broadcaster app documentation to navigation

doc(navigation.json): broadcaster app

---

public/navigation.json

docs(navigation): add master data pagination guide

---

public/navigation.json

chore(navigation.json): update list of io apps

---

public/navigation.json

EDU-13282 Added documentation

---

public/navigation.json

Refers to [#1381](https://github.com/vtexdocs/dev-portal-content/pull/1381)

docs(navigation.json): styling

---

netlify.toml

- Redirect from `https://developers.vtex.com/docs/guides/vtex-wordpress-integration` to `https://developers.vtex.com/docs/apps/vtex.wordpress-integration`

docs(netlify.toml): redirect wordpress integration

---

public/navigation.json

Fix (navigation.json): rename FastStore UI Components name (Molecules)

---

public/navigation.json

Reference: https://github.com/vtexdocs/dev-portal-content/pull/1173

Feat (navigation.json): hide FastStore UI documentation (Getting started)

---

netlify.toml

EDU-11692 Redirected link

---

public/navigation.json

Reference: https://github.com/vtexdocs/dev-portal-content/pull/1477

Fix (navigation.json): Organisms components' name

---

public/navigation.json

fix: personal shopper navigation.json

---

public/navigation.json

Adding new endpoints do Orders API navigation.

Adding new Change order settings endpoints to navigation

---

public/navigation.json

EDU-13322 New sidebar tradeName

---

public/navigation.json

docs(navigation): add master data guide

---

netlify.toml
public/navigation.json

docs(navigation): edit master data guides

---

src/components/last-updates-section/index.tsx

fix(last-updates-section/index.tsx)

---

public/navigation.json

EDU-11062 Sidebar Create price table

---

public/navigation.json

fix(navigation.json): fix hooks and components slug

---

netlify.toml
public/navigation.json

Reference: https://github.com/vtexdocs/dev-portal-content/pull/1500

fix(navigation.json): update FastStore title and slug name (updating-the-cli-package-version)

---

netlify.toml

Redirect to Enable the Region for SKUs.
Redirect article with broken link.

EDU-8935 | new-redirect to Enable the Region for SKUs

---

public/navigation.json
src/components/last-updates-section/index.tsx

Reference: https://github.com/vtexdocs/dev-portal-content/pull/1520

EDU-13580: Update navigation.json - New WebOps release note

---

public/navigation.json
src/components/last-updates-section/index.tsx

Reference: https://github.com/vtexdocs/dev-portal-content/pull/1525

EDU-13709: Update 'navigation.json' - WebOps release note

---

netlify.toml
public/navigation.json

- Added **Dealing with events** category cover to sidebar.
- Created redirect from /docs/guides/dealing-with-events to /docs/guides/store-framework-dealing-with-events.
Refers to [#1439](https://github.com/vtexdocs/dev-portal-content/pull/1439)

doc(navigation.json): dealing with events

---

public/navigation.json

- Updating slug
- Refers to [#1410](https://github.com/vtexdocs/dev-portal-content/pull/1410)

docs(navigation.json): updating live stores

---

public/navigation.json

Added a new troubleshooting article to the navigation and reorganized the troubleshooting section navigation alphabetically.
Reference: https://github.com/vtexdocs/dev-portal-content/pull/1501

feat(navigation.json): [EDU-12862] Troubleshooting API extensions

---

.github/workflows/docsearch-scraper.yml
algolia/scraper_openapi.json
algolia/scripts/scraper.sh

feat: adjust docsearch-scraper action considering pr #5

---

netlify.toml
public/navigation.json

Working with Site Editor - fixing slug on sidebar and redirect

---

package.json

chore(package.json): update components package version

---

src/components/breadcrumb/index.tsx
src/components/breadcrumb/styles.ts
src/pages/docs/guides/[slug].tsx
src/pages/updates/release-notes/[slug].tsx
src/utils/getTroubleshootingData.ts
src/utils/navigation-utils.ts

feat(release-notes): add pagination

---

netlify.toml
public/navigation.json

chore(navigation.json): update navigation file

---

netlify.toml

EDU-10057 and EDU-10090 Redirect link

---

netlify.toml
public/navigation.json

- Added [*Optimizing image rendering*](https://developers.vtex.com/docs/guides/vtex-io-documentation-optimizing-image-rendering) guide to sidebar
- Created the redirect from `/docs/guides/vtex-io-documentation-best-practices-for-rendering-images` to `/docs/guides/vtex-io-documentation-optimizing-image-rendering`
Refers to PR [#1540](https://github.com/vtexdocs/dev-portal-content/pull/1540)

Edu 13730 review rendering images

---

public/navigation.json

Reference: https://github.com/vtexdocs/dev-portal-content/pull/1527

EDU-13694: feat(navigation.json)

---

public/navigation.json

Reference: https://github.com/vtexdocs/dev-portal-content/pull/1535

EDU-12075: feat(navigation.json) - My pages are taking too long to be published on Headless CMS

---

public/navigation.json

chore(navigation.json): update navigation

---

netlify.toml

EDU-13819 Redirect link

---

netlify.toml

EDU-11238 Redirect link

---

public/navigation.json
src/components/last-updates-section/index.tsx

chore(navigation.json): add rn to navigation file

---

public/navigation.json

Update navigation.json: organizing FastStore section + adding FastStore SDK category

EDU-13483: Add FastStore SDK category

---

src/components/last-updates-section/index.tsx

fix: update last-updates-section

---

public/navigation.json

EDU-14041: Update navigation.json

---

public/navigation.json

EDU-13987: [FastStore release note] Update navigation.json

---

public/navigation.json

Reference: https://github.com/vtexdocs/dev-portal-content/pull/1662

add(navigation.json): 2025 release note category

---

public/navigation.json

EDU-13472: Update navigation.json

---

public/navigation.json

Reference: https://github.com/vtexdocs/dev-portal-content/pull/1653/files

EDU-13833: Release note (Update navigation.json)

---

netlify.toml

EDU-13945 Redirect links

---

public/navigation.json

Refers to [#1617](https://github.com/vtexdocs/dev-portal-content/pull/1617)

docs(navigation.json): adding doc to sidebar

---

src/components/last-updates-section/index.tsx

Update 'last-updates-card' index.tsx

---

public/navigation.json

Refers to [#1654](https://github.com/vtexdocs/dev-portal-content/pull/1654)

docs(navigation.json): adding advanced layout docs to sidebar

---

netlify.toml
public/navigation.json

Reference: https://github.com/vtexdocs/dev-portal-content/pull/1683

EDU-14195 (navigation.json): Update FastStore go live steps

---

netlify.toml

[EDU-14257](https://vtex-dev.atlassian.net/browse/EDU-14257)

docs: create redirect for architecture guide

---

netlify.toml
public/navigation.json

Refers to [#1598](https://github.com/vtexdocs/dev-portal-content/pull/1598)

Docs/Configuring Analytics on Store Framework

---

netlify.toml

[EDU-11257](https://vtex-dev.atlassian.net/browse/EDU-11257)

docs(netlify.toml): performance

---

netlify.toml
public/navigation.json

- Added the category cover *Managing performance* to sidebar
- Fixed redirect to `/docs/guides/vtex-io-documentation-enabling-performance-settings`

Category cover: Managing performance

---

public/navigation.json
src/pages/api/openapi/[slug].tsx
src/pages/api/postman/[slug].tsx
src/utils/getReferencePaths.ts

Add the Pick and Pack Order Changes API to Developer Portal

[EDU-13992] feat: add pick and pack order changes api

---

netlify.toml

[EDU-7862](https://vtex-dev.atlassian.net/browse/EDU-7862)

docs(netlify.toml): SEO

---

netlify.toml
public/navigation.json

Fix (navigation.json): Troubleshooting slug for "I can’t install the Headless CMS plugins in my account" guide.

---

netlify.toml

Fix: Troubleshooting redirect

---

netlify.toml
public/navigation.json

Refers to [EDU-14254](https://vtex-dev.atlassian.net/browse/EDU-14254). Must be merged with [vtexdocs/dev-portal-content/#1710](https://github.com/vtexdocs/dev-portal-content/pull/1710).

EDU-14254 - Change and redirect order modifications slugs

---

public/navigation.json

Refers to [#1658](https://github.com/vtexdocs/dev-portal-content/pull/1658)

docs(navigation.json): accessibility

---

public/navigation.json

EDU-14413 Updated name in the sidebar

---

netlify.toml

EDU-14389 Redirect link

---

netlify.toml
public/navigation.json

remove deprecated master data guide

---

public/navigation.json

docs(navigation.json): add session client app and graphql

---

netlify.toml
public/navigation.json

docs(navigation.json): add marketplace integration app graphql

---

netlify.toml

Fix: Experimental exports redirect

---

public/navigation.json

docs(navigation): add token renewal endpoints

---

public/navigation.json

add(navigation.json): FastStore overview category doc page

---

.gitignore
Dockerfile
README.md
docker-compose.yml
package.json
yarn.lock

This PR adds a dockerfile that teaches Docker how to run this in a container
This makes the devmode work seamlessly in every machine capable of running docker

feat(dockerfile): add dockerfile for running devmode

---

public/navigation.json

relates to https://github.com/vtexdocs/dev-portal-content/pull/1699 and should only be merged after it

docs(navigation): add payments release notes

---

public/navigation.json

relates to https://github.com/vtex/openapi-schemas/pull/1377 (should only be merged after it)

docs(navigation): add payment notification endpoints

---

public/navigation.json

Fix sidebar

---

public/navigation.json

feat(navigation.json): New FastStore SEO docs

---

public/navigation.json
src/components/last-updates-section/index.tsx

feat(navigation.json): add FastStore release note (EDU14349)

---

src/components/last-updates-section/index.tsx

feat(index.tsx): update 'last-updates-section'

---

public/navigation.json

docs(navigation.json): move apps troubleshooting

---

netlify.toml

EDU-12149 Redirect link Pricing API

---

public/navigation.json

feat(navigation.json): add new FastStore guide

---

public/navigation.json

feat(navigation.json): add FastStore Search guides

---

public/navigation.json

docs(navigation.json): add Messages app doc and API reference

---

public/navigation.json

add https://github.com/vtexdocs/dev-portal-content/pull/1746 release notes to navigation

docs(navigation): add vtex id release notes

---

public/navigation.json

EDU-14557-Added release notes to sidebar

---

public/navigation.json

EDU-14660 added endpoint to sidebar

---

public/navigation.json
src/pages/api/openapi/[slug].tsx
src/pages/api/postman/[slug].tsx

Add the Operational Capacity API to navigation

EDU-14390 feat: add Operational Capacity API to navigation

---

netlify.toml
public/navigation.json

feat(navigation.json): update FastStore SEO category and fix docs redirects

---

src/utils/getReferencePaths.ts

EDU-14390-add-Operational-Capacity-API

---

public/navigation.json

Reference: https://github.com/vtexdocs/dev-portal-content/pull/1757

feat(navigation.json): EDU-14516 - Add Session guide

---

public/navigation.json

feat: add operational capacity api release note to navigation

---

public/navigation.json

relates to https://github.com/vtexdocs/dev-portal-content/pull/1832

docs(navigation): remove deprecated guide

---

public/navigation.json

Reference: https://github.com/vtexdocs/dev-portal-content/pull/1835

docs(navigation.json): remove FastStore and Ad Network integration guide

---

public/navigation.json

Reference: https://github.com/vtexdocs/dev-portal-content/pull/1823

docs(navigation.json): Add 'Sending custom events' guide

---

public/navigation.json

Reference: https://github.com/vtexdocs/dev-portal-content/pull/1678

docs(navigation.json): add FastStore Cart overview

---

src/components/faststore-components/Modal/ModalBase.tsx

chore(modalbase.tsx): add ModalFooter to FastStore Modal usage example

---

src/pages/api/openapi/[slug].tsx
src/pages/docs/api-reference/[slug].tsx

The current OpenAPI specification delivery system in our docs portal relies solely on jsDelivr for fetching OpenAPI files, without any fallback mechanisms or cache freshness validation. During build time, the system also encounters errors when trying to resolve relative API URLs as file paths.
This pull request introduces significant improvements to the OpenAPI specification fetching mechanism and ensures proper URL handling during both server-side rendering (SSR) and client-side rendering. The most important changes include the addition of new functions to fetch OpenAPI specs from multiple sources with caching and logging, and modifications to ensure URLs are correctly formed during build time.
* `src/pages/api/openapi/[slug].tsx`: Added `fetchFromJsdelivr` and `fetchFromGithubRaw` …

feat(api): improve OpenAPI spec delivery with tiered caching strategy

---

src/pages/api/openapi/[slug].tsx
src/pages/docs/api-reference/[slug].tsx

fix(api): correct SwaggerParser options for handling circular references

---

ARCHITECTURE.md
src/components/auth/index.tsx
src/pages/_app.tsx
src/pages/api/auth/[...nextauth].js
src/pages/api/preview.ts
src/utils/contexts/auth.tsx

This pull request introduces significant updates to the VTEX Developer Portal, including a comprehensive architectural documentation and enhancements to the authentication system. The main changes are detailed below:
* [`ARCHITECTURE.md`](diffhunk://#diff-8f6366fd8e7a5fa30f7f05879999195b7cf5fa1e3d157822eb37f0e91d226cfdR1-R210): Added an extensive overview of the VTEX Developer Portal architecture, including the tech stack, core concepts, file structure, key subsystems, page types, data flow, performance optimizations, development practices, deployment, external integrations, and best practices.
* [`src/components/auth/index.tsx`](diffhunk://#diff-3c9f3927ed65c44c0224567e9bdc222f98e17c484e48a63dce13658e670776e7L1-R30): Updated the `Auth` component to use a custom `useAuth` hook, which …

Auth performance improvements

---

public/navigation.json

Conversational Commerce is deprecated

docs: remove Conversational Commerce from navigation

---

netlify.toml

Add a new redirect for checkout api

EDU-8800 feat: update netlify.toml / add redirect

---

public/navigation.json

Refers to [#1799](https://github.com/vtexdocs/dev-portal-content/pull/1799)
Added `FastStore WebOps: Improved the integration with the Headless CMS` to the sidebar.

Docs/EDU-14697-FastStore WebOps: Improved the integration with the Headless CMS

---

public/navigation.json
src/pages/api/openapi/[slug].tsx
src/pages/api/postman/[slug].tsx
src/utils/getReferencePaths.ts

Add the new Delivery Promise Notification API

feat: add delivery promise api

---

src/pages/api/openapi/[slug].tsx
src/pages/api/postman/[slug].tsx
src/utils/getReferencePaths.ts

fix(getreferencepaths): fix prettier issues

---

public/navigation.json

Add Delivery Promise Notification API release note to navigation

EDU-14815 feat: add delivery promise api release note

---

public/navigation.json

Changing navigation Delete category from subcollection endpoint path

---

public/navigation.json

Refers to [#1858](https://github.com/vtexdocs/dev-portal-content/pull/1858)
Added `RatingField` to sidebar.

docs/EDU-14918 - RatingField

---

public/navigation.json

Reference: https://github.com/vtexdocs/dev-portal-content/pull/1847

docs(navigation.json): add `useCart` guide

---

public/navigation.json

Reference: https://github.com/vtexdocs/dev-portal-content/pull/1849/files

docs(navigation.json): add FastStore GraphQL cache control guide

---

public/navigation.json
src/components/last-updates-section/index.tsx

Reference: https://github.com/vtexdocs/dev-portal-content/pull/1857

docs(navigation.json): add new FastStore release note

---

public/navigation.json

Reference: https://github.com/vtexdocs/dev-portal-content/pull/1845

docs(navigation.json): Release note - FastStore: Improved breadcrumb navigation

---

public/navigation.json

https://github.com/vtexdocs/dev-portal-content/pull/1891

docs(navigation.json): add new sdk doc

---

public/navigation.json

docs(navigation.json): add section cover "graphql in vtex io"

---

public/navigation.json

docs(navigation.json): fix guide slug

---

public/navigation.json

Add new affiliate endpoints to Marketplace API and its release note

feat: add new affiliate endpoints

---

src/pages/docs/apps/[slug]/[child].tsx

chore(apps/[slug]/[child].tsx): add remarkMermaid

---

public/navigation.json

Refers to [#1894](https://github.com/vtexdocs/dev-portal-content/pull/1894)

docs(navigation.json): my account faststore

---

public/navigation.json

Refers to [#1821](https://github.com/vtexdocs/dev-portal-content/pull/1821)
Adding `Tooltip` to the sidebar.

docs(navigation.json): EDU-14484 - adding `Tooltip` to the sidebar

---

public/navigation.json

Refers to [#1808](https://github.com/vtexdocs/dev-portal-content/pull/1808) (`Textarea`) e [#1820](https://github.com/vtexdocs/dev-portal-content/pull/1820) (`TextareaField`)

docs(navigation.json): adding `Textarea` and `TextareaField` to sidebar

---

netlify.toml

Redirects 404 page to the correct link. Refers to [EDU-11170](https://vtex-dev.atlassian.net/browse/EDU-11170).

EDU-11170 - Fix 404

---

public/navigation.json

docs(navigation.json): removing my account docs from sidebar

---

public/navigation.json

Refers to [#1797](https://github.com/vtexdocs/dev-portal-content/pull/1797)
Added `Glossary` to sidebar.

docs/EDU-14333 - Store Framework glossary

---

public/navigation.json
src/components/last-updates-section/index.tsx

Reference: https://github.com/vtexdocs/dev-portal-content/pull/1919/files

docs(navigation.json): FastStore new release note (SEO flags)

---

netlify.toml

Fixes URL for redirect. Refers to [EDU-11170](https://vtex-dev.atlassian.net/browse/EDU-11170).

EDU 11170 - Fix URL for redirect

---

public/navigation.json

https://github.com/vtexdocs/dev-portal-content/pull/1932

docs(navigation.json): Validating UTM tracking

---

public/navigation.json
src/components/last-updates-section/index.tsx

https://github.com/vtexdocs/dev-portal-content/pull/1905

docs(navigation.json): Release note: new experimental flag'graphqlCacheControl

---

netlify.toml

EDU-15072  redirect document

---

public/navigation.json

fix: ssl-certificates-api navigation

---

public/navigation.json

doc(navigation.json): add graphql api list

---

netlify.toml

creating a redirect for the gift list app documentation, as suggested in https://github.com/vtexdocs/dev-portal-content/pull/1832

add gift list redirect

---

src/components/subscription-list/index.tsx
src/utils/get-url.tsx

PR created to implement real-time email verification. This feature uses Check-Mail.org (free of charge) to ensure that incorrect emails are not added to the Intercom sending list. 
Note: The implementation of this functionality was a request from the Intercom team, after we received a high number of hard bounces in the email addresses of the first version of the VTEX Newsletter Documentation.

Add email validation to subscription list

---

public/navigation.json

Refers to [#1986](https://github.com/vtexdocs/dev-portal-content/pull/1986)

docs(navigation.json): release note deprecated apps

---

public/navigation.json

Refers to [#1719](https://github.com/vtexdocs/dev-portal-content/pull/1719)

docs(navigation.json): overriding native app blocks

---

public/navigation.json

Refers to [#1917](https://github.com/vtexdocs/dev-portal-content/pull/1917)

docs(navigation.json): secrets

---

netlify.toml

Adds to [PR #983](https://github.com/vtexdocs/devportal/pull/983).

Add Gift List subpages redirect

---

public/navigation.json

docs: add ssl certificates documentation to navigation

---

public/navigation.json

Reference: https://github.com/vtexdocs/dev-portal-content/pull/1959

docs(navigation.json): New FastStore release note

---

public/navigation.json

Refers to [#2003](https://github.com/vtexdocs/dev-portal-content/pull/2003)

EDU-15086: FastStore Secrets (Release note)

---

public/navigation.json

docs(navigation.json): seo-overview

---

public/navigation.json

docs(navigation.json): add "GraphQL Authorization in VTEX IO"

---

public/navigation.json

docs(navigation.json): new faststore analytics guide

---

public/navigation.json
src/pages/api/openapi/[slug].tsx
src/pages/api/postman/[slug].tsx
src/utils/getReferencePaths.ts

feat: add punchout api

---

public/navigation.json
src/pages/api/openapi/[slug].tsx
src/pages/api/postman/[slug].tsx
src/utils/getReferencePaths.ts

feat: add mTLS api

---

public/navigation.json

Adding new release note to navigation

Adding to navigation release note about subcollection

---

public/navigation.json

docs: add identity guides to navigation

---

src/components/last-updates-section/index.tsx

docs(index.tsx): fix 'type'

---

netlify.toml

Redirect:
from `docs/guides/vtex-product-context` to `docs/apps/vtex.product-context`

Product context redirect

---

netlify.toml

Fix redirect - Delivery Promise

---

public/navigation.json

update: add finish punchout endpoint to navigation

---

public/navigation.json
src/components/last-updates-section/index.tsx

docs(navigation.json): new release note

---

public/navigation.json

Added the new Delivery Promise documentation to the Logistics category

feat: add delivery promise doc

---

package.json
src/pages/_app.tsx
src/styles/global.css

feat(package.json): install fontawesome

---

public/navigation.json

EDU-15167 Added new sidebar

---

package.json
public/navigation.json
src/pages/server-sitemap.xml/index.ts
src/utils/navigation-utils.ts

chore(package.json): update @vtexdocs/components

---

algolia/scraper_md.json
algolia/scraper_openapi.json

chore(algolia): update scraper for compatibility with components package

---

src/pages/_app.tsx

chore(_app.tsx): update metadata

---

public/navigation.json

docs(navigation.json): add "Integrating an app with a GraphQL API"

---

src/pages/docs/apps/[slug]/[child].tsx
src/pages/docs/apps/[slug]/index.tsx
src/pages/docs/guides/[slug].tsx
src/pages/docs/troubleshooting/[slug].tsx
src/styles/documentation-page.ts
src/utils/serializeWithFallback.ts

fix(serializewithfallback): update md and mdx options
